In [1]:
import numpy as np
import pandas as pd

### 데이터 프레임 생성
- 2차원 리스트
- 리스트를 가지고 있는 딕셔너리
- 딕셔너리를 가지고 있는 리스트
- 딕셔너리를 가지고 있는 디셔너리
- 외부파일 (csv, 엑셀, spss, sas 등등)
- 웹 문서에 있는 table 태그
- 데이터 베이스의 테이블
- Series들을 모아서 생성
- 기타 등등

In [8]:
# 2차원 리스트를 통한 생성
# 각 리스트의 순서가 일치하는 것끼리 모아서 하나의 컬럼으로 구성된다
# 다른 리스트보다 값이 더 많거나 부족하면
# 오류가 발생하지 않고 결측치로 채워주게 된다.

list1 = [
    [1, '남자', 90, 80, 70],
    [2, '여자', 91, 81, 71],
    [3, '남자', 92, 82, 72],
    [4, '여자', 93, 83, 73],
    [5, '남자', 94, 84],
    [6, '여자', 95, 85, 75, 65]
]

df1 = pd.DataFrame(list1)

In [9]:
print(type(df1))

<class 'pandas.DataFrame'>

In [10]:
print(df1)
display(df1)

   0   1   2   3     4     5
0  1  남자  90  80  70.0   NaN
1  2  여자  91  81  71.0   NaN
2  3  남자  92  82  72.0   NaN
3  4  여자  93  83  73.0   NaN
4  5  남자  94  84   NaN   NaN
5  6  여자  95  85  75.0  65.0

   0   1   2   3     4     5
0  1  남자  90  80  70.0   NaN
1  2  여자  91  81  71.0   NaN
2  3  남자  92  82  72.0   NaN
3  4  여자  93  83  73.0   NaN
4  5  남자  94  84   NaN   NaN
5  6  여자  95  85  75.0  65.0

In [13]:
# 데이터 프레임을 생성할 때 index나 컬럼 이름을 지정하지 않으면
# 0부터 1씩 증가되는 것으로 지정된다.
# 그리고 index나 컬럼 이름을 지정하면서 만들수도 있다.
a1 = ['번호','성별','국어','영어','수학','과학']
a2 = ['학생1','학생2','학생3','학생4','학생5','학생6']

df2 = pd.DataFrame(list1, index=a2, columns=a1)
df2

     번호  성별  국어  영어    수학    과학
학생1   1  남자  90  80  70.0   NaN
학생2   2  여자  91  81  71.0   NaN
학생3   3  남자  92  82  72.0   NaN
학생4   4  여자  93  83  73.0   NaN
학생5   5  남자  94  84   NaN   NaN
학생6   6  여자  95  85  75.0  65.0

In [14]:
# 이미 만들어져 있는 데이터 프레임에 index나 컬럼 이름을 지정하여 변경할 수 있다.
display(df1)

df1.columns= a1
df1.index= a2

display(df1)

   0   1   2   3     4     5
0  1  남자  90  80  70.0   NaN
1  2  여자  91  81  71.0   NaN
2  3  남자  92  82  72.0   NaN
3  4  여자  93  83  73.0   NaN
4  5  남자  94  84   NaN   NaN
5  6  여자  95  85  75.0  65.0

     번호  성별  국어  영어    수학    과학
학생1   1  남자  90  80  70.0   NaN
학생2   2  여자  91  81  71.0   NaN
학생3   3  남자  92  82  72.0   NaN
학생4   4  여자  93  83  73.0   NaN
학생5   5  남자  94  84   NaN   NaN
학생6   6  여자  95  85  75.0  65.0

In [19]:
# 리스트를 가지고 있는 딕셔너리
# 딕셔너리가 가지고 있는 리스트 각각이 컬럼으로 구성된다
# 리스트의 이름이 컬럼의 이름이 된다
# 만약 값의 개수가 다른 리스트가 있다면 오류가 발생한다
data1 = {
    '번호' : [1,2,3,4],
    '성별' : ['남자','여자','남자','여자'],
    '국어' : [90,91,92,93],
    '영어' : [80,81,82,83],
    '수학' : [70,71,72,73],
    #'과학' : [60,61,62,63,64],
    #'한국사' : [50,51,52]
    '물리' : [60,61,62,np.nan]
}
df1 = pd.DataFrame(data1)
display(df1)

   번호  성별  국어  영어  수학    물리
0   1  남자  90  80  70  60.0
1   2  여자  91  81  71  61.0
2   3  남자  92  82  72  62.0
3   4  여자  93  83  73   NaN

In [23]:
# 딕셔너리를 가지고 있는 리스트
# 각 딕셔너리의 이름이 동일한 것끼리 묶어서 컬럼으로 구성한다
# 만약 이름이 없는 딕셔너리가 있다면 그 부분은 결측치로 채워진다.
list3 = [
    {'번호' : 1, '이름': '홍길동', '국어': 100},
    {'번호' : 2, '이름': '김길동', '국어': 101},
    {'번호' : 3, '이름': '박길동', '국어': 102},
    {'번호' : 4, '이름': '최길동'},
    {'번호' : 4, '이름': '최길동', '한국사': 104},
]
df4 = pd.DataFrame(list3)
df4

   번호   이름     국어    한국사
0   1  홍길동  100.0    NaN
1   2  김길동  101.0    NaN
2   3  박길동  102.0    NaN
3   4  최길동    NaN    NaN
4   4  최길동    NaN  104.0

In [30]:
# 딕셔너리를 가지고 있는 딕셔너리
dict10 = {
    '번호' : {'학생1' : 1, '학생2':2, '학생3':3},
    '이름' : {'학생1' : '홍길동', '학생2' : '김길동', '학생3' : '고길동'},
    '국어' : {'학생1' : 100, '학생2' : 200, '학생3' : 300},
    '영어' : {'학생1' : 101, '학생2' : 201},
    '수학' : {'학생1' : 103, '학생4' : 104},
}
df10 = pd.DataFrame(dict10)
df10

      번호   이름     국어     영어     수학
학생1  1.0  홍길동  100.0  101.0  103.0
학생2  2.0  김길동  200.0  201.0    NaN
학생3  3.0  고길동  300.0    NaN    NaN
학생4  NaN  NaN    NaN    NaN  104.0

In [32]:
# csv 파일 
# 콤마(,)로 데이터를 구분한 양식

# csv 파일은 콤마로 구분하여 저장해놓은 텍스트 파일이다.
# 텍스트 파일의 특징은 데이터만 파일에 기록되어 있고 다른 부가적인 정보는 없다.

df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [34]:
# 만약 특정 번째의 행을 컬럼 명으로 사용하고 그 다음부터 데이터로 사용하고자 한다면..
# header = 컬럼명으로 사용할 행의 순서값을 넣어준다
df2 = pd.read_csv('data/grade.csv',encoding='euc-kr',header=2)
df2

   영희  2  여자   88  90    62    72
0  민수  1  남자   92  70   NaN   NaN
1  수현  3  여자   63  60  31.0  70.0
2  호영  4  남자  120  50   NaN  88.0

In [35]:
# 만약 첫 줄부터 데이터라면
df3 = pd.read_csv('data/grade.csv', encoding='euc-kr', header=None)
df3

    0   1   2    3    4    5    6
0  이름  학년  성별   국어   영어   수학   과학
1  철수   1  남자   98  NaN   88   64
2  영희   2  여자   88   90   62   72
3  민수   1  남자   92   70  NaN  NaN
4  수현   3  여자   63   60   31   70
5  호영   4  남자  120   50  NaN   88

In [37]:
# 엑셀 파일로 부터 읽어와 데이터 프레임을 생성한다
# openpyxl 라이브러리 필요

df1 = pd.read_excel('data/grade.xlsx')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [38]:
# sheet_name을 이용하면 원하는 시트를 지정하여 데이터 프레임을 생성한다.
df1 = pd.read_excel('data/grade.xlsx', sheet_name='grade')
df2 = pd.read_excel('data/grade.xlsx', sheet_name='grade2')

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

    이름  학년  성별   국어    영어    수학    과학
0  홍길동   1  남자   98   NaN  88.0  64.0
1   영희   2  여자   88  90.0  62.0  72.0
2   민수   1  남자   92  70.0   NaN   NaN
3   수현   3  여자   63  60.0  31.0  70.0
4   호영   4  남자  120  50.0   NaN  88.0

In [39]:
# sheet_name에 정수를 설정하면 시트의 순서가 된다
df1 = pd.read_excel('data/grade.xlsx', sheet_name =0)
df2 = pd.read_excel('data/grade.xlsx', sheet_name =1)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

    이름  학년  성별   국어    영어    수학    과학
0  홍길동   1  남자   98   NaN  88.0  64.0
1   영희   2  여자   88  90.0  62.0  72.0
2   민수   1  남자   92  70.0   NaN   NaN
3   수현   3  여자   63  60.0  31.0  70.0
4   호영   4  남자  120  50.0   NaN  88.0

In [45]:
# 웹 페이지에 있는 table 태그를 통해 데이터 프레임을 생성한다
# lxml 라이브러리 필요

df1 = pd.read_html('https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx?sort=HRA_RT')
for df_temp in df1 :
    display(df_temp)

# 해당 주소의 웹 문서안에 있는 모든 table 태그를 이용하여 데이터 프레임을 생성한다.
# table 태그 하나당 하나의 데이터 프레임을 생성하고 그 데이터 프레임들을 가지고 있는 리스트가 반환된다.
df_list = pd.read_html('https://www.basketball-reference.com/boxscores/')
for df_temp in df_list :
    display(df_temp)

    순위   선수명   팀명    AVG   G   PA   AB   R    H  2B  3B  HR   TB  RBI  SAC  SF
0    1   최원준   KT  0.365  75  359  307  66  112  20   3   7  159   44    3   3
1    2   이우성   NC  0.354  72  280  263  30   93  15   0   6  126   34    1   1
2    3   오스틴   LG  0.350  78  346  300  63  105  16   3  24  199   75    0   3
3    4   박성한  SSG  0.339  78  341  286  54   97  18   1   3  126   36    0   2
4    5  레이예스   롯데  0.339  77  341  304  37  103  17   1  10  152   54    0   3
5    6   박민우   NC  0.339  73  308  254  47   86  17   0   4  115   45    1   3
6    7   구자욱   삼성  0.330  59  254  215  41   71  14   3   7  112   50    0   4
7    8   최형우   삼성  0.328  74  317  259  35   85  14   0   9  126   57    0   6
8    9   페라자   한화  0.319  76  342  282  66   90  21   1  17  164   51    2   4
9   10   김주원   NC  0.311  75  337  293  51   91  14   0  12  141   36    1   3
10  11   강백호   한화  0.307  72  316  280  44   86  17   0  19  160   77    0   2
11  12   김민석   두산  0.307  71  255  225  32   69  13   2   4   98   28    1   1
12  13   김현수   KT  0.303  75  338  304  36   92  21   0   5  128   50    0   2
13  14   김지찬   삼성  0.298  75  289  238  56   71   5   2   0   80   21    7   2
14  15  힐리어드   KT  0.297  76  340  300  58   89  14   3  19  166   64    0   4
15  16    최정  SSG  0.296  63  269  223  39   66  13   1  18  135   49    0   5
16  17   김도영  KIA  0.295  79  342  292  63   86  15   1  25  178   69    0   2
17  18   김상수   KT  0.294  68  265  221  22   65   6   1   0   73   23    5   1
18  19   박승규   삼성  0.293  62  239  198  42   58   8   5   9  103   33    0   2
19  20   박해민   LG  0.292  78  304  253  46   74  11   0   3   94   32   11   6
20  21   정준재  SSG  0.292  75  303  257  39   75   8   5   1   96   27   11   5
21  22   류지혁   삼성  0.291  74  292  247  36   72  12   4   4  104   40    4   1
22  23   박건우   NC  0.290  73  292  248  37   72   9   0  14  123   47    0   9
23  24  데이비슨   NC  0.290  63  252  221  23   64  11   1   8  101   40    0   2
24  25   디아즈   삼성  0.289  77  346  305  44   88  15   0  15  148   68    0   3
25  26   나성범  KIA  0.287  75  306  265  44   76  16   0  15  137   42    0   2
26  27   카메론   두산  0.287  75  314  279  39   80  19   3   9  132   43    0   2
27  28   문현빈   한화  0.282  74  339  291  49   82  18   4   9  135   47    1   3
28  29   전민재   롯데  0.282  74  269  245  26   69  11   0   8  104   42    2   3
29  30   김호령  KIA  0.281  78  334  302  46   85  17   1  11  137   46    5   5

             0   1      2
0     New York  94  Final
1  San Antonio  90    NaN

    Unnamed: 0   1   2   3   4
0     New York  13  24  28  29
1  San Antonio  23  19  30  18

     0                  1   2
0  PTS     J. Brunson-NYK  45
1  TRB  V. Wembanyama-SAS  14

      Eastern Conference   W   L   W/L%    GB   PS/G   PA/G
0       Detroit Pistons*  60  22  0.732     —  117.8  109.6
1        Boston Celtics*  56  26  0.683   4.0  114.9  107.2
2       New York Knicks*  53  29  0.646   7.0  116.5  110.1
3   Cleveland Cavaliers*  52  30  0.634   8.0  119.5  115.4
4         Atlanta Hawks*  46  36  0.561  14.0  118.5  116.0
5       Toronto Raptors*  46  36  0.561  14.0  114.6  111.8
6    Philadelphia 76ers*  45  37  0.549  15.0  115.9  116.1
7         Orlando Magic*  45  37  0.549  15.0  115.7  115.1
8      Charlotte Hornets  44  38  0.537  16.0  116.0  111.2
9             Miami Heat  43  39  0.524  17.0  120.9  118.5
10       Milwaukee Bucks  32  50  0.390  28.0  110.6  116.8
11         Chicago Bulls  31  51  0.378  29.0  116.3  121.5
12         Brooklyn Nets  20  62  0.244  40.0  105.9  115.9
13        Indiana Pacers  19  63  0.232  41.0  112.4  120.4
14    Washington Wizards  17  65  0.207  43.0  112.9  124.9

         Western Conference   W   L   W/L%    GB   PS/G   PA/G
0    Oklahoma City Thunder*  64  18  0.780     —  119.0  107.9
1        San Antonio Spurs*  62  20  0.756   2.0  119.8  111.5
2           Denver Nuggets*  54  28  0.659  10.0  122.1  116.9
3       Los Angeles Lakers*  53  29  0.646  11.0  116.3  114.6
4          Houston Rockets*  52  30  0.634  12.0  115.2  110.0
5   Minnesota Timberwolves*  49  33  0.598  15.0  118.0  114.6
6             Phoenix Suns*  45  37  0.549  19.0  112.6  111.1
7   Portland Trail Blazers*  42  40  0.512  22.0  115.5  115.8
8      Los Angeles Clippers  42  40  0.512  22.0  113.8  112.6
9     Golden State Warriors  37  45  0.451  27.0  114.6  115.2
10     New Orleans Pelicans  26  56  0.317  38.0  115.5  120.0
11         Dallas Mavericks  26  56  0.317  38.0  114.1  119.6
12        Memphis Grizzlies  25  57  0.305  39.0  114.7  120.7
13         Sacramento Kings  22  60  0.268  42.0  111.0  121.0
14                Utah Jazz  22  60  0.268  42.0  117.6  126.0

In [47]:
# 데이터 베이스 연동하여 데이터 프레임을 생성한다.
# mysql 대상으로 코드만 짤 예정
# pymysql, cryptography 라이브러리 필요
import pymysql

# 데이터 베이스 접속 정보를 관리하는 객체
db_connector = pymysql.connect(
    # DBMS가 설치되어 있는 컴퓨터의 IP 주소
    host = '127.0.0.1',
    # DBMS의 포트번호
    port = 3306,
    # 접속할 계정
    user = '계정 아이디',
    # 비밀번호
    password = '비밀번호',
    # 사용할 데이터베이스 이름
    db = '데이터베이스 이름',
    # 인코딩 타입
    charset = 'utf8'
)

# select 쿼리문
# select 쿼리문을 수행해 가져온 결과를 데이터 프레임으로 생성한다.
sql = 'select 쿼리문'

df100 = pd.read_sql(sql, db_connector)
df100

UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-3: ordinal not in range(256)