In [1]:
import numpy as np
import pandas as pd

### 전체 데이터 가져오기

In [3]:
# Series
s1 = pd.Series([10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# Series.values 를 사용하면 ndarray 형태로 값들을 가져온다.
array1 = s1.values
array1

array([10, 20, 30, 40, 50])

In [5]:
# 데이터 프레임 생성

In [8]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [13]:
# DataFrame.values
# 데이터 프레임에 있는 숫자나 날짜 타입의 값이 아닌 다른 타입의 값은 원래 Object 타입으로 취급해서 관리한다.
# 문자열의 경우 str로 표기되지만 내부적으로는 object 타입으로 관리가 된다.
# 이에 문자열 컬럼이 있는 데이터 프레임의 데이터를 행렬로 가져오면 전체의 타입이 object 타입으로 결정된다.
# 이 때문에 행렬안에 들어있는 값들을 원래의 타입형태로 가져다 사용하는 것이 가능하다.
array2 = df1.values
array2

array([['철수', 1, '남자', 98, nan, 88.0, 64.0],
       ['영희', 2, '여자', 88, 90.0, 62.0, 72.0],
       ['민수', 1, '남자', 92, 70.0, nan, nan],
       ['수현', 3, '여자', 63, 60.0, 31.0, 70.0],
       ['호영', 4, '남자', 120, 50.0, nan, 88.0]], dtype=object)

In [14]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   학년      5 non-null      int64
 2   성별      5 non-null      str
 3   국어      5 non-null      int64
 4   영어      4 non-null      float64
 5   수학      3 non-null      float64
 6   과학      4 non-null      float64
dtypes: float64(3), int64(2), str(2)
memory usage: 412.0 bytes

### 행이나 열 가져오기

In [16]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.index = ['학생1','학생2','학생3','학생4','학생5']
df1

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [17]:
# 특정 컬럼의 값을 가져온다.
# 지정된 컬럼의 값들을 모두 추출하여 Series로 생성하여 반환한다.
s1 = df1['국어']
s1

학생1     98
학생2     88
학생3     92
학생4     63
학생5    120
Name: 국어, dtype: int64

In [22]:
# loc : index를 통해 하나의 행을 데이터를 가져온다.
# 지정된 행의 데이터를 모두 추출하여 Series로 생성해준다.
# 이 때, Series의 index는 데이터 프레임의 컬럼의 이름으로 지정된다.
s2 = df1.loc['학생2']
s2

이름      영희
학년       2
성별      여자
국어      88
영어    90.0
수학    62.0
과학    72.0
Name: 학생2, dtype: object

In [23]:
# iloc : 순서를 통해 행 하나의 값을 가져온다.
# 가져온 값을 통해 Series로 생성해주고 컬럼의 이름을 index로 지정해준다.
s3 = df1.iloc[2]
s3

이름      민수
학년       1
성별      남자
국어      92
영어    70.0
수학     NaN
과학     NaN
Name: 학생3, dtype: object

In [26]:
# 데이터 프레임['컬럼명']['index']
# 1. 전체 데이터 프레임에서 지정된 컬럼의 데이터를 모두 추출해 Series로 생성한다.
# 2. 생성된 Series에서 지정된 index에 해당하는 행들의 값을 가져온다.
a1 = df1['국어']['학생1']
a1

np.int64(98)

In [28]:
# 데이터프레임[] 는 무조건 컬럼명을 지칭하는 것으로 처리를 한다
# 이 때문에 컬럼명을 통해 컬럼에 접근하고 index를 통해 행에 접근하는 것이 아닌 
# ('국어', '학생') 형태로 되어 있는 컬럼을 찾으려고 하기 때문에 오류가 발생한다.
a2 = df1['국어']['학생1']
a2

np.int64(98)

In [33]:
# loc 사용
# 데이터프레임.loc['index']['컬럼명']

# 아래의 문법은 데이터 프레임에서 '학생1'이라는 index에 해당하는 행의 데이터를 모두 추출해서 새로운 Series를 생성
# 그 후 새롭게 생성된 Series에서 '성별' 이라는 index에 해당하는 행의 데이터를 가져온다.
a1 = df1.loc['학생1']['성별']
a1

'남자'

In [32]:
# 데이터 프레임에서 index가 학생1이고 컬럼명이 성별인 곳에 직접 접근하여 데이터를 가져온다.
a1 = df1.loc['학생1','성별']
a1

'남자'

In [35]:
# iloc[순서값][컬럼명]
# 데이터 프레임에서 순서값2(3 번째) 행의 데이터를 모두 추출하여 새로운 Series를 생성
# 그 후, 새롭게 생성된 Series에서 국어라는 index에 해당하는 행의 데이터를 가져온다.
a1 = df1.iloc[2]['국어']
a1

np.int64(92)

In [37]:
# iloc는 무조건 순서값을 지정해야한다.
# 그래서 [] 안에 무조건 순서값이 들어가야한다.
a1 = df1.iloc[2, '국어']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [38]:
# 데이터 프레임에 직접 접근하여 순서값2에 해당하는 행, 순서값 2에 해당하는 컬럼에 접근하여 값을 가져온다.
a1 = df1.iloc[2,2]
a1

'남자'

### 값을 저장한다.

In [42]:
display(df1)

# '과학'컬럼, '학생4' index에 해당하는 곳에 5000을 넣어준다.
# 아래의 코드는 데이터 프레임에서 '과학'이라는 컬럼에 해당하는 값을 모두 추출하여 새로운 Series를 생성한다.
# 새롭게 생성된 Series에 접근하여 '학생4'라는 index의 행에 5000을 넣어준다.
# 이에 원본 데이터 프레임에는 반영되지 않는다.(pandas 2.x 버전까지는 예외로 값을 원본 데이터 프레임에 반영시켜줬었음)
# 데이터 프레임의 값을 변경한다면 데이터 프레임에 직접 접근하는 방식을 사용해야한다.
df1['과학']['학생4'] = 5000

display(df1)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

C:\Users\dokim\AppData\Local\Temp\ipykernel_8284\7151391.py:8: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df1['과학']['학생4'] = 5000

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [48]:
display(df1)
# 원본 데이터 프레임이 아닌 index가 학생3인 행의 데이터를 추출하여 
# 새롭게 만든 Series에 접근하여 2000을 넣어주는 것이므로 원본 데이터 프레임에는 값이 변경되지 않는다.
df1.loc['학생3']['영어'] = 2000

df1

     이름  학년  성별   국어      영어    수학    과학
학생1  철수   1  남자   98     NaN  88.0  64.0
학생2  영희   2  여자   88    90.0  62.0  72.0
학생3  민수   1  남자   92  2000.0   NaN   NaN
학생4  수현   3  여자   63    60.0  31.0  70.0
학생5  호영   4  남자  120    50.0   NaN  88.0

C:\Users\dokim\AppData\Local\Temp\ipykernel_8284\1205847092.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df1.loc['학생3']['영어'] = 2000

     이름  학년  성별   국어      영어    수학    과학
학생1  철수   1  남자   98     NaN  88.0  64.0
학생2  영희   2  여자   88    90.0  62.0  72.0
학생3  민수   1  남자   92  2000.0   NaN   NaN
학생4  수현   3  여자   63    60.0  31.0  70.0
학생5  호영   4  남자  120    50.0   NaN  88.0

In [46]:
display(df1)

# 원본 데이터 프레임에 접근하여 값을 넣어주는 것이 아닌 순서값 2에 해당하는 행의 데이터
# 모두 추출해서 새롭게 만든 Series의 순서값2에 해당하는 행에 값을 넣는 것이므로
# 원본 데이터 프레임에는 반영되지 않는다.
df1.iloc[2][2] = 5000

display(df1)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

C:\Users\dokim\AppData\Local\Temp\ipykernel_8284\3478156283.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df1.iloc[2][2] = 5000

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [47]:
# loc[index, 컬럼명]

display(df1)

# 데이터 프레임에 직접 접근하여 index가 학생3인 행 , 컬럼명이 영어인 열에 접근하는 그 부분에 
# 값을 넣어주므로 데이터 프레임에 반영된다.
df1.loc['학생3','영어'] = 2000
display(df1)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별   국어      영어    수학    과학
학생1  철수   1  남자   98     NaN  88.0  64.0
학생2  영희   2  여자   88    90.0  62.0  72.0
학생3  민수   1  남자   92  2000.0   NaN   NaN
학생4  수현   3  여자   63    60.0  31.0  70.0
학생5  호영   4  남자  120    50.0   NaN  88.0

In [50]:
display(df1)

# 데이터 프레임에서 순서값 3에 해당하는 행, 순서값 3에 해당하는 컬럼에 직접 접근하여 값을 넣어주므로
# 데이터 프레임에 반영된다.
df1.iloc[3,3] = 5000

display(df1)

     이름  학년  성별    국어      영어    수학    과학
학생1  철수   1  남자    98     NaN  88.0  64.0
학생2  영희   2  여자    88    90.0  62.0  72.0
학생3  민수   1  남자    92  2000.0   NaN   NaN
학생4  수현   3  여자  5000    60.0  31.0  70.0
학생5  호영   4  남자   120    50.0   NaN  88.0

     이름  학년  성별    국어      영어    수학    과학
학생1  철수   1  남자    98     NaN  88.0  64.0
학생2  영희   2  여자    88    90.0  62.0  72.0
학생3  민수   1  남자    92  2000.0   NaN   NaN
학생4  수현   3  여자  5000    60.0  31.0  70.0
학생5  호영   4  남자   120    50.0   NaN  88.0

In [52]:
# copy함수 : 데이터 프레임을 복제하여 새로운 데이터 프레임을 생성한다.
df2 = df1.copy()

df2.loc['학생2','국어'] = 6000
display(df1)
display(df2)

     이름  학년  성별    국어      영어    수학    과학
학생1  철수   1  남자    98     NaN  88.0  64.0
학생2  영희   2  여자    88    90.0  62.0  72.0
학생3  민수   1  남자    92  2000.0   NaN   NaN
학생4  수현   3  여자  5000    60.0  31.0  70.0
학생5  호영   4  남자   120    50.0   NaN  88.0

     이름  학년  성별    국어      영어    수학    과학
학생1  철수   1  남자    98     NaN  88.0  64.0
학생2  영희   2  여자  6000    90.0  62.0  72.0
학생3  민수   1  남자    92  2000.0   NaN   NaN
학생4  수현   3  여자  5000    60.0  31.0  70.0
학생5  호영   4  남자   120    50.0   NaN  88.0

### 슬라이싱

In [55]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.index = ['학생1','학생2','학생3','학생4','학생5']
df1

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [59]:
# 다수의 컬럼을 가져온다.
# 원본 접근 X (새로운 데이터 프레임을 생성한다.)
# 새롭게 생성되는 데이터 프레임의 컬럼의 순서는 작성한 컬럼의 순서가 된다.

a1 = df1[['국어','학년','과학']]
a1

      국어  학년    과학
학생1   98   1  64.0
학생2   88   2  72.0
학생3   92   1   NaN
학생4   63   3  70.0
학생5  120   4  88.0

In [61]:
# 다수의 index를 지정하여 데이터를 가져온다.
# 원본 접근 X (새로운 데이터 프레임을 생성한다.)
# index에 해당하는 행들을 모아 새로운 데이터 프레임을 생성한다.
a2 = df1.loc[['학생3','학생1','학생4']]
a2

     이름  학년  성별  국어    영어    수학    과학
학생3  민수   1  남자  92  70.0   NaN   NaN
학생1  철수   1  남자  98   NaN  88.0  64.0
학생4  수현   3  여자  63  60.0  31.0  70.0

In [63]:
# 행의 순서값들을 지정하여 다수의 행을 가져온다.
# 원본 접근 X
# 순서값에 해당하는 행들을 모두 추출하여 새로운 데이터 프레임을 생성
a3 = df1.iloc[[3,0,2]]
a3

     이름  학년  성별  국어    영어    수학    과학
학생4  수현   3  여자  63  60.0  31.0  70.0
학생1  철수   1  남자  98   NaN  88.0  64.0
학생3  민수   1  남자  92  70.0   NaN   NaN

In [66]:
# 열과 행을 지정해서 가져온다.
# 원본접근 X
# 데이터 프레임에서 '국어', '영어' 컬럼 데이터들을 추출하여 새로운 데이터 프레임을 생성한다.
# 그 후, 새롭게 생성된 데이터 프레임에서 index가 학생1, 학생3에 해당하는 행을 추출하여 새로운 데이터 프레임 생성
a1 = df1[['국어','영어']].loc[['학생1','학생3']]
a1

     국어    영어
학생1  98   NaN
학생3  92  70.0

In [71]:
# 원본 접근 X
# 데이터 프레임에서 학생1, 학생2에 해당하는 행의 데이터를 추출하여 새로운 데이터 프레임을 생성
# 그 후, 새롭게 생성된 데이터 프레임에서 국어, 수학 컬럼을 추출하여 새로운 데이터 프레임을 생성한다.
a5 = df1.loc[['학생1','학생2']][['국어','수학']]
a5

     국어    수학
학생1  98  88.0
학생2  88  62.0

In [74]:
# 원본 데이터 접근 O
# 데이터 프레임에서 학생1, 학생3에 해당하는 행, 국어, 수학에 해당하는 컬럼 부분에 접근하여
# 데이터를 추출한 다음 새로운 데이터 프레임을 생성한다.
a6 = df1.loc[['학생1','학생3'],['국어','수학']]
a6

     국어    수학
학생1  98  88.0
학생3  92   NaN

In [79]:
# iloc
# 원본 접근 X
# 데이터 프레임에서 순서값 0,2에 해당하는 행을 추출하여 새로운 데이터 프레임을 생성한다.
# 그 후, 새롭게 생성된 데이터 프레임에서 국어와 수학 컬럼에 해당하는 값들을 추출하여 새로운 데이터 프레임 생성
a7 = df1.iloc[[0,2]][['국어','수학']]

a7

     국어    수학
학생1  98  88.0
학생3  92   NaN

In [81]:
# 데이터 프레임에서 0, 2 번째 행 3,5번쨰 컬럼에 해당하는 값을 데이터 프레임에서 직접가져와서
# 새로운 데이터 프레임을 생성한다.
a8 = df1.iloc[[0,2],[3,5]]
a8

     국어    수학
학생1  98  88.0
학생3  92   NaN

In [83]:
df2 = df1.copy()
# 컬럼 하나를 지정하여 값 하나를 넣어주면 해당 컬럼의 값들을 모두 변경해준다.
display(df2)

df2['국어'] = 1000

display(df2)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별    국어    영어    수학    과학
학생1  철수   1  남자  1000   NaN  88.0  64.0
학생2  영희   2  여자  1000  90.0  62.0  72.0
학생3  민수   1  남자  1000  70.0   NaN   NaN
학생4  수현   3  여자  1000  60.0  31.0  70.0
학생5  호영   4  남자  1000  50.0   NaN  88.0

In [84]:
df3 = df1.copy()

# 컬럼이 가진 행들의 값을 각각 다르게 설정한다.
# 이 때, 행의 개수와 동일한 개수의 값을 지정해야한다.
display(df2)

df2['국어'] = [1000, 2000, 3000, 4000, 5000]

display(df2)

     이름  학년  성별    국어    영어    수학    과학
학생1  철수   1  남자  1000   NaN  88.0  64.0
학생2  영희   2  여자  1000  90.0  62.0  72.0
학생3  민수   1  남자  1000  70.0   NaN   NaN
학생4  수현   3  여자  1000  60.0  31.0  70.0
학생5  호영   4  남자  1000  50.0   NaN  88.0

     이름  학년  성별    국어    영어    수학    과학
학생1  철수   1  남자  1000   NaN  88.0  64.0
학생2  영희   2  여자  2000  90.0  62.0  72.0
학생3  민수   1  남자  3000  70.0   NaN   NaN
학생4  수현   3  여자  4000  60.0  31.0  70.0
학생5  호영   4  남자  5000  50.0   NaN  88.0

In [89]:
df2 = df1.copy()

display(df2)
# index를 지정하여 값을 넣어줄 때 하나의 값만 넣어주면 해당 행의 모든 컬럼의 값을 똑같이 설정할 수 있다.
df2 = df2.astype('str')
df2.loc['학생2'] = '새로운 문자열'

display(df2)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

          이름       학년       성별       국어       영어       수학       과학
학생1       철수        1       남자       98      NaN     88.0     64.0
학생2  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열
학생3       민수        1       남자       92     70.0      NaN      NaN
학생4       수현        3       여자       63     60.0     31.0     70.0
학생5       호영        4       남자      120     50.0      NaN     88.0

In [91]:
# 컬럼의 개수만큼 값을 지정하면 각각 따로 값을 지정할 수 있다.
df2 = df1.copy()

display(df2)
df2.loc['학생2'] = ['오징어', 100, '어류', 1,2,3,4]
display(df2)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

      이름   학년  성별   국어    영어    수학    과학
학생1   철수    1  남자   98   NaN  88.0  64.0
학생2  오징어  100  어류    1   2.0   3.0   4.0
학생3   민수    1  남자   92  70.0   NaN   NaN
학생4   수현    3  여자   63  60.0  31.0  70.0
학생5   호영    4  남자  120  50.0   NaN  88.0

In [93]:
df2 = df1.copy()
df2 = df2.astype('str')

display(df2)

# 순서값을 통해 특정행을 지정하고 하나의 값을 넣어주면 그 행의 모든 컬럼에 동일한 값이 설정된다.
df2.iloc[1] = '새로운 문자열'

display(df2)

     이름 학년  성별   국어    영어    수학    과학
학생1  철수  1  남자   98   NaN  88.0  64.0
학생2  영희  2  여자   88  90.0  62.0  72.0
학생3  민수  1  남자   92  70.0   NaN   NaN
학생4  수현  3  여자   63  60.0  31.0  70.0
학생5  호영  4  남자  120  50.0   NaN  88.0

          이름       학년       성별       국어       영어       수학       과학
학생1       철수        1       남자       98      NaN     88.0     64.0
학생2  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열  새로운 문자열
학생3       민수        1       남자       92     70.0      NaN      NaN
학생4       수현        3       여자       63     60.0     31.0     70.0
학생5       호영        4       남자      120     50.0      NaN     88.0

In [95]:
# 컬럼의 개수에 맞게 값을 넣어주면 각각 변경된다.
df2 = df1.copy()

display(df2)

df2.iloc[1] = ['돌고래', 1000, '포유류', 500, 600, 700, 800]

display(df2)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

      이름    학년   성별   국어     영어     수학     과학
학생1   철수     1   남자   98    NaN   88.0   64.0
학생2  돌고래  1000  포유류  500  600.0  700.0  800.0
학생3   민수     1   남자   92   70.0    NaN    NaN
학생4   수현     3   여자   63   60.0   31.0   70.0
학생5   호영     4   남자  120   50.0    NaN   88.0

In [98]:
# 다수의 컬럼을 지정하여 데이터를 변경한다.
df2 = df1.copy()
df3 = df1.copy()

# 국어, 수학 컬럼에 같은 값을 담아준다
display(df2)
df2[['국어','영어']] = 1000
display(df2)

# 국어, 수학 컬럼에 각각 다른 값을 담아준다
display(df3)
df3[['국어','영어']] = [1000,2000]
display(df3)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별    국어    영어    수학    과학
학생1  철수   1  남자  1000  1000  88.0  64.0
학생2  영희   2  여자  1000  1000  62.0  72.0
학생3  민수   1  남자  1000  1000   NaN   NaN
학생4  수현   3  여자  1000  1000  31.0  70.0
학생5  호영   4  남자  1000  1000   NaN  88.0

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별    국어    영어    수학    과학
학생1  철수   1  남자  1000  2000  88.0  64.0
학생2  영희   2  여자  1000  2000  62.0  72.0
학생3  민수   1  남자  1000  2000   NaN   NaN
학생4  수현   3  여자  1000  2000  31.0  70.0
학생5  호영   4  남자  1000  2000   NaN  88.0

In [102]:
# loc
df2 = df1.copy()

df2.astype('str')

df2.loc['학생1','학생3'] = '새로운 문자열1'

# df2.loc['학생3','학생4'] = ['새로운 문자열2', '새로운문자열3']

df2

     이름  학년  성별   국어    영어    수학    과학       학생3
학생1  철수   1  남자   98   NaN  88.0  64.0  새로운 문자열1
학생2  영희   2  여자   88  90.0  62.0  72.0       NaN
학생3  민수   1  남자   92  70.0   NaN   NaN       NaN
학생4  수현   3  여자   63  60.0  31.0  70.0       NaN
학생5  호영   4  남자  120  50.0   NaN  88.0       NaN

In [107]:
df2 = df1.copy()

df2.loc[['학생1','학생3'],['국어','수학']] = [[100,200],[300,400]]

df2

     이름  학년  성별   국어    영어     수학    과학
학생1  철수   1  남자  100   NaN  200.0  64.0
학생2  영희   2  여자   88  90.0   62.0  72.0
학생3  민수   1  남자  300  70.0  400.0   NaN
학생4  수현   3  여자   63  60.0   31.0  70.0
학생5  호영   4  남자  120  50.0    NaN  88.0

In [108]:
df2 = df1.copy()
df2.iloc[[1,3],[4,6]] = [[1000,2000],[3000,4000]]
df2

     이름  학년  성별   국어      영어    수학      과학
학생1  철수   1  남자   98     NaN  88.0    64.0
학생2  영희   2  여자   88  1000.0  62.0  2000.0
학생3  민수   1  남자   92    70.0   NaN     NaN
학생4  수현   3  여자   63  3000.0  31.0  4000.0
학생5  호영   4  남자  120    50.0   NaN    88.0

In [110]:
# 범위를 지정하여 일부를 가져온다.
# 컬럼은 서로가 독립성을 가진 요소이기 때문에 어디~어디 라는 범위의 개념이 없다
# 아래와 같은 코드를 수행하면 아무것도 가져오지 못한다.
df1['학년':'수학']

Empty DataFrame
Columns: [이름, 학년, 성별, 국어, 영어, 수학, 과학]
Index: []

In [113]:
# index
# 학생2 ~ 학생4
display(df1.loc['학생2':'학생4'])

display(df1.loc[:'학생4'])
display(df1.loc['학생2':])

     이름  학년  성별  국어    영어    수학    과학
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별  국어    영어    수학    과학
학생1  철수   1  남자  98   NaN  88.0  64.0
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별   국어    영어    수학    과학
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [115]:
# 순서값
# 순거밧 1 ~ 4 -1까지
display(df1.iloc[1:4])
display(df1.iloc[:4])
display(df1.iloc[2:])

     이름  학년  성별  국어    영어    수학    과학
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별  국어    영어    수학    과학
학생1  철수   1  남자  98   NaN  88.0  64.0
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별   국어    영어    수학    과학
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [117]:
# 위에서 살펴봤던 df1['학년':'수학']는 컬럼이 아닌 index의 범위를 지정한 것이다
# 이에 학년과 수학이라는 index가 없기 때문에 아무것도 못가져온 것이다.
display(df1['학생2':'학생4'])
display(df1[:'학생4'])
display(df1['학생2':])

     이름  학년  성별  국어    영어    수학    과학
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별  국어    영어    수학    과학
학생1  철수   1  남자  98   NaN  88.0  64.0
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별   국어    영어    수학    과학
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [118]:
# 데이터 프레임의 index가 숫자가 아닐 때 [ : ] 에 숫자를 넣어주면 순서값된다.
display(df1[1:4])
display(df1[:4])
display(df1[1:])

     이름  학년  성별  국어    영어    수학    과학
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별  국어    영어    수학    과학
학생1  철수   1  남자  98   NaN  88.0  64.0
학생2  영희   2  여자  88  90.0  62.0  72.0
학생3  민수   1  남자  92  70.0   NaN   NaN
학생4  수현   3  여자  63  60.0  31.0  70.0

     이름  학년  성별   국어    영어    수학    과학
학생2  영희   2  여자   88  90.0  62.0  72.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생4  수현   3  여자   63  60.0  31.0  70.0
학생5  호영   4  남자  120  50.0   NaN  88.0

In [119]:
# True나 False로 구성되어 있는 것을 넣으면 True에 해당하는 행을 가져온다
a1 =df1[[True, False, True, False, True]]
a2 =df1.loc[[True, False, True, False, True]]
a3 =df1.iloc[[True, False, True, False, True]]

display(a1)
display(a2)
display(a3)

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생5  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별   국어    영어    수학    과학
학생1  철수   1  남자   98   NaN  88.0  64.0
학생3  민수   1  남자   92  70.0   NaN   NaN
학생5  호영   4  남자  120  50.0   NaN  88.0