### 데이터 전처리
- 전처리란 어떠한 작업을 하기 전에 그 작업을 위한 처리를 의미한다.
- 컬럼 이름이나 인덱스를 변경
- 행과 열의 순서를 변경
- 데이터 정렬
- 데이터 검색
- 행, 열 추가
- 행, 열 삭제
- 행, 열의 값을 변경
- 두 개 이상의 데이터 프레임을 병합
- 결측치 처리
- 이상치 처리
- 기타 등등

### inplace
- 데이터 프레임의 변형을 가하는 함수들은 원본을 변경하거나 원본을 유지하고 작업이 반영된 새로운 데이터 프레임을 생성한다.
- 만약 변형을 가하는 함수에 inplace라는 매개변수가 있다면 개발자에게 선택권을 준 것이다.
- inplace에 True를 넣어주면 원본이 변경되고 False를 넣어주면 원본은 유지한채 새로운 데이터 프레임을 생성한다.
- 앞으로 만드는 예제 중에서 inplace가 있는 함수들은 inplace에 True를 넣어서 작업을 한다.
  (복습 할 때 inplace가 있다는 것을 기억하게 하기 위해서)

### 만약 inplace가 없다면~
- 함수가 원본을 변경시키는 것만 제공하는 경우
- 함수가 원본을 유지시키고 새로운 데이터 프레임을 생성하는 것만 제공하는 경우
- 원본을 유지하는 함수와 원본을 변경시키는 함수를 각각 따로 제공하는 경우

### axis
- 작업을 반영하는 기준이나, 작업을 하기 위해 그룹을 묶는 기준을 설정한다.
- 0 이면 행 기준
- 1 이면 열 기준

### axis가 없다면~
- 행에 대해서만 작업을 하는 함수인 경우
- 열에 대해서만 작업을 하는 함수인 경우
- columns라는 매개변수나 index라는 매개변수가 제공되는 경우
- 행이나 열에 대해서 작업하는 함수가 각각 따로 제공되는 경우

In [1]:
import numpy as np
import pandas as pd

### 행,열의 순서를 변경

In [2]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [3]:
# reindex : 행이나 열의 순서를 변경한다는 의미를 가진 함수
# 열 순서 변경 : 지정된 컬럼 데이터를 지정된 순서대로 가져온다.
# 원본은 유지하고 새로운 데이터 프레임을 생성한다.
df2=df1.reindex(columns=['과학','수학','영어','국어','성별','학년','이름'])

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

     과학    수학    영어   국어  성별  학년  이름
0  64.0  88.0   NaN   98  남자   1  철수
1  72.0  62.0  90.0   88  여자   2  영희
2   NaN   NaN  70.0   92  남자   1  민수
3  70.0  31.0  60.0   63  여자   3  수현
4  88.0   NaN  50.0  120  남자   4  호영

In [4]:
# 컬럼 이름을 일부만 지정하면 일부만 가져오는 효과를 얻을 수 있다.
df3 = df1.reindex(columns = ['국어','영어','수학'])
df3

    국어    영어    수학
0   98   NaN  88.0
1   88  90.0  62.0
2   92  70.0   NaN
3   63  60.0  31.0
4  120  50.0   NaN

In [6]:
# 원본 데이터 프레임에 없는 컬럼의 이름을 지정하면...
# 없는 이름의 컬럼이 결과에 포함되고 데이터는 결측치로 채워진다.
df4 = df1.reindex(columns = ['국어','영어','한국사'])
df4

    국어    영어  한국사
0   98   NaN  NaN
1   88  90.0  NaN
2   92  70.0  NaN
3   63  60.0  NaN
4  120  50.0  NaN

In [8]:
# 행의 순서를 변경한다.(index를 지정한다
df2 = df1.reindex(index=[4,1,3,0,2])
display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
1  영희   2  여자   88  90.0  62.0  72.0
3  수현   3  여자   63  60.0  31.0  70.0
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN

In [10]:
# 일부만 지정하면 일부만 가져온다.
df3 = df1.reindex(index=[3,0,1])
df3

   이름  학년  성별  국어    영어    수학    과학
3  수현   3  여자  63  60.0  31.0  70.0
0  철수   1  남자  98   NaN  88.0  64.0
1  영희   2  여자  88  90.0  62.0  72.0

In [11]:
# 없는 index를 지정하면 결과에 추가되고 결측치로 채워진다
df4 = df1.reindex([3,0,10])
df4

     이름   학년   성별    국어    영어    수학    과학
3    수현  3.0   여자  63.0  60.0  31.0  70.0
0    철수  1.0   남자  98.0   NaN  88.0  64.0
10  NaN  NaN  NaN   NaN   NaN   NaN   NaN

In [12]:
# 같이 사용하는 것도 가능하다
df2 = df1.reindex(columns = ['성별','과학','이름'], index = [3,0,4])
df2

   성별    과학  이름
3  여자  70.0  수현
0  남자  64.0  철수
4  남자  88.0  호영

In [13]:
# [ ], loc, iloc : 지정한 것을 가져온다라는 의미를 가진다.
# 모든 컬럼을 작성해주면 순서대로 가져온다
df2 = df1[['과학','수학','영어','국어','성별','학년','이름']]
display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

     과학    수학    영어   국어  성별  학년  이름
0  64.0  88.0   NaN   98  남자   1  철수
1  72.0  62.0  90.0   88  여자   2  영희
2   NaN   NaN  70.0   92  남자   1  민수
3  70.0  31.0  60.0   63  여자   3  수현
4  88.0   NaN  50.0  120  남자   4  호영

In [14]:
# 일부만 지정하면 일부만 가져온다
df2 = df1[['국어','영어','수학']]
df2

    국어    영어    수학
0   98   NaN  88.0
1   88  90.0  62.0
2   92  70.0   NaN
3   63  60.0  31.0
4  120  50.0   NaN

In [16]:
# 없는 컬럼명을 지정하면 오류가 발생한다.
df2 = df1[['영어','수학','한국사']]
df2

KeyError: "['한국사'] not in index"

In [17]:
# loc : index를 통해 행을 가져온다.
df2 = df1.loc[[4,0,1,3,2]]
df3 = df1.loc[[3,0,1]]

display(df1)
display(df2)
display(df3)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
3  수현   3  여자   63  60.0  31.0  70.0
2  민수   1  남자   92  70.0   NaN   NaN

   이름  학년  성별  국어    영어    수학    과학
3  수현   3  여자  63  60.0  31.0  70.0
0  철수   1  남자  98   NaN  88.0  64.0
1  영희   2  여자  88  90.0  62.0  72.0

In [18]:
# 없는 것을 지정하면 오류가 발생한다
df4 = df1.loc[[3,0,10]]
df4

KeyError: '[10] not in index'

In [19]:
# iloc : 지정된 순서 값 번째의 행을 가져온다
df2 = df1.iloc[[4,3,2,1,0]]
df3 = df1.iloc[[3,0,1]]

display(df1)
display(df2)
display(df3)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
3  수현   3  여자   63  60.0  31.0  70.0
2  민수   1  남자   92  70.0   NaN   NaN
1  영희   2  여자   88  90.0  62.0  72.0
0  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별  국어    영어    수학    과학
3  수현   3  여자  63  60.0  31.0  70.0
0  철수   1  남자  98   NaN  88.0  64.0
1  영희   2  여자  88  90.0  62.0  72.0

In [20]:
# 없는 순서 값을 지정하면 오류가 발생한다.
df4 = df1.iloc[[3,0,10]]
df4

IndexError: positional indexers are out-of-bounds

In [21]:
# filter : 원본 데이터 프레임에서 지정한 것 외는 다 걸러낸다는 의미를 가지고 있다.
# axis를 통해서 행, 열 지정한다.
# 생략 시 컬럼이 기준이 된다.
df2 = df1.filter(['과학','수학','영어','국어','성별','학년','이름'])
df3 = df1.filter(['국어','영어','과학'])

display(df1)
display(df2)
display(df3)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

     과학    수학    영어   국어  성별  학년  이름
0  64.0  88.0   NaN   98  남자   1  철수
1  72.0  62.0  90.0   88  여자   2  영희
2   NaN   NaN  70.0   92  남자   1  민수
3  70.0  31.0  60.0   63  여자   3  수현
4  88.0   NaN  50.0  120  남자   4  호영

    국어    영어    과학
0   98   NaN  64.0
1   88  90.0  72.0
2   92  70.0   NaN
3   63  60.0  70.0
4  120  50.0  88.0

In [23]:
# 지정한 컬럼들 중 원본 데이터 프레임에 없는 것은 결과에서 제외된다.
df4 = df1.filter(['국어','영어','한국사'])
df4

    국어    영어
0   98   NaN
1   88  90.0
2   92  70.0
3   63  60.0
4  120  50.0

In [24]:
# axis에 0을 넣어주면 index를 통해 행을 가져온다.
df2 = df1.filter([4,1,3,0,2], axis = 0)
df3 = df1.filter([3,0,2], axis = 0)
df4 = df1.filter([3,0,10],axis = 0)

display(df1)
display(df2)
display(df3)
display(df4)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
1  영희   2  여자   88  90.0  62.0  72.0
3  수현   3  여자   63  60.0  31.0  70.0
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN

   이름  학년  성별  국어    영어    수학    과학
3  수현   3  여자  63  60.0  31.0  70.0
0  철수   1  남자  98   NaN  88.0  64.0
2  민수   1  남자  92  70.0   NaN   NaN

   이름  학년  성별  국어    영어    수학    과학
3  수현   3  여자  63  60.0  31.0  70.0
0  철수   1  남자  98   NaN  88.0  64.0

### 컬럼 이름과 인덱스를 변경한다.

In [25]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [26]:
# 전체 변경
df2 = df1.copy()

# 컬럼의 이름을 변경할 때는 모든 컬럼을 지정해줘야 한다.
df2.columns = ['c1','c2','c3','c4','c5','c6','c7']

# index를 변경할 때는 모든 index를 지정해줘야 한다.
df2.index = ['r1','r2','r3','r4','r5']

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

    c1  c2  c3   c4    c5    c6    c7
r1  철수   1  남자   98   NaN  88.0  64.0
r2  영희   2  여자   88  90.0  62.0  72.0
r3  민수   1  남자   92  70.0   NaN   NaN
r4  수현   3  여자   63  60.0  31.0  70.0
r5  호영   4  남자  120  50.0   NaN  88.0

In [29]:
# 일부만 변경하고자 할 때

# 딕셔너리에 저장하는 데이터의 구조를 이용한다.
# 이름 : 원래의 이름
# 값 : 새로운 이름

df2 = df1.copy()

a1 = {
    '국어' : 'korean',
    '영어' : 'english'
}

a2={
    0 : '학생1',
    2 : '학생3'
}

df2.rename(columns=a1, index=a2, inplace=True)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

     이름  학년  성별  korean  english    수학    과학
학생1  철수   1  남자      98      NaN  88.0  64.0
1    영희   2  여자      88     90.0  62.0  72.0
학생3  민수   1  남자      92     70.0   NaN   NaN
3    수현   3  여자      63     60.0  31.0  70.0
4    호영   4  남자     120     50.0   NaN  88.0

### 데이터 정렬

In [30]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [33]:
# 특정 컬럼을 기준으로 오름차순 정렬
df2 = df1.copy()

df2.sort_values('국어', inplace=True)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
3  수현   3  여자   63  60.0  31.0  70.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
0  철수   1  남자   98   NaN  88.0  64.0
4  호영   4  남자  120  50.0   NaN  88.0

In [37]:
# 특정 컬럼을 기준으로 내림차순 정렬
df2 = df1.copy()

df2.sort_values('영어', inplace=True, ascending=False)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0

In [38]:
# 정렬 시 결측치 확인
# 정렬의 기준이 되는 컬럼에 결측치가 있는 행은 무조건 제일 아래로 내려간다.
df2 = df1.copy()

df3 = df2.sort_values('영어')
df4 = df2.sort_values('영어', ascending=False)

display(df3)
display(df4)

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
3  수현   3  여자   63  60.0  31.0  70.0
2  민수   1  남자   92  70.0   NaN   NaN
1  영희   2  여자   88  90.0  62.0  72.0
0  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0

In [39]:
# 정렬의 기준이 되는 컬럼을 다수 설정했을 경우
# 첫 번째 기준으로 정렬을 한다.
# 첫 번째 기준이 되는 컬럼의 값이 같은 것 끼리 그룹으로 묶은 후 각 그룹 내에서
# 두 번째 기준이 되는 컬럼을 기준으로 정렬한다.
df2 = df1.copy()

# ascending 을 생략하면 모든 정렬이 오름차순 정렬이다.
df2.sort_values(['성별','국어'], inplace=True)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
2  민수   1  남자   92  70.0   NaN   NaN
0  철수   1  남자   98   NaN  88.0  64.0
4  호영   4  남자  120  50.0   NaN  88.0
3  수현   3  여자   63  60.0  31.0  70.0
1  영희   2  여자   88  90.0  62.0  72.0

In [40]:
# 만약 ascending에 False를 설정하면 두 정렬 모두 내림 차순 정렬을 수행한다.
df2 = df1.copy()

df2.sort_values(['성별','국어'], inplace=True,ascending=False)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN

In [41]:
# 만약 정렬 방식을 각각 설정하고 싶다면..
df2 = df1.copy()

df2.sort_values(['성별','국어'],inplace = True, ascending=[True,False])

df2

   이름  학년  성별   국어    영어    수학    과학
4  호영   4  남자  120  50.0   NaN  88.0
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
1  영희   2  여자   88  90.0  62.0  72.0
3  수현   3  여자   63  60.0  31.0  70.0

In [42]:
# index를 통한 정렬
# 정렬 테스트를 위해서 index를 새롭게 지정한다.
df2 = df1.copy()

df2.index = [4,1,2,0,3]

df2

   이름  학년  성별   국어    영어    수학    과학
4  영희   2  여자   88  90.0  62.0  72.0
1  민수   1  남자   92  70.0   NaN   NaN
2  수현   3  여자   63  60.0  31.0  70.0
0  호영   4  남자  120  50.0   NaN  88.0
3  철수   1  남자   98   NaN  88.0  64.0

In [47]:
df3 = df2.copy()

# index를 기준으로 오름차순 정렬을 한다.
df3.sort_index(inplace=True)
display(df2)
display(df3)

   이름  학년  성별   국어    영어    수학    과학
4  영희   2  여자   88  90.0  62.0  72.0
1  민수   1  남자   92  70.0   NaN   NaN
2  수현   3  여자   63  60.0  31.0  70.0
0  호영   4  남자  120  50.0   NaN  88.0
3  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
0  호영   4  남자  120  50.0   NaN  88.0
1  민수   1  남자   92  70.0   NaN   NaN
2  수현   3  여자   63  60.0  31.0  70.0
3  철수   1  남자   98   NaN  88.0  64.0
4  영희   2  여자   88  90.0  62.0  72.0

In [49]:
# index를 기준으로 내림차순 정렬
df3 = df2.copy()
df3.sort_index(inplace=True, ascending=False)

display(df2)
display(df3)

   이름  학년  성별   국어    영어    수학    과학
4  영희   2  여자   88  90.0  62.0  72.0
1  민수   1  남자   92  70.0   NaN   NaN
2  수현   3  여자   63  60.0  31.0  70.0
0  호영   4  남자  120  50.0   NaN  88.0
3  철수   1  남자   98   NaN  88.0  64.0

   이름  학년  성별   국어    영어    수학    과학
4  영희   2  여자   88  90.0  62.0  72.0
3  철수   1  남자   98   NaN  88.0  64.0
2  수현   3  여자   63  60.0  31.0  70.0
1  민수   1  남자   92  70.0   NaN   NaN
0  호영   4  남자  120  50.0   NaN  88.0