In [1]:
import numpy as np
import pandas as pd

### 조건에 만족하는 데이터를 검색해온다.
- 조건에 만족하는 행들을 가지고와 새로운 데이터 프레임을 생성한다.

In [42]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [44]:
# 원래는 데이터 프레임 [ ] 방식으로 접근하면 컬럼을 선택하는 것이다.
# 하지만 True나 False로 구성되어 있는 것을 넣어주면 True에 해당하는 행들을 가져올 수 있다.
df2 = df1[[True,False,True,False,True]]
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

In [45]:
# 이를 이용해 조건에 만족하는 행들을 가져오는 작업을 할 수 있다.
# df2 = df1['국어']>90 로 하면 True/False 반환
# 아래의 코드는 df1['국어']를 통해 국어 컬럼의 값을 Series로 가져온다.
# Series와 > 90 라는 연산을 통해 90 보다 큰 값은 True 아닌 것은 False로 구성되어 있는 Series를 가져온다.
# 그 Series를 데이터 프레임 [ ] 안에넣어주었기 때문에 True에 해당하는 행들을 가져온다.
# 즉, 이것은 검색의 기능이 아닌 True, False로 구성된 것을 넣어주면 True에 해당하는 행만 가져온다는 것을 이용한 것이다.
df2 = df1[df1['국어']>90]
df2

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

In [10]:
# 데이터 프레임은 검색을 위한 함수를 제공하고 있다.
# 특정 컬럼의 값을 비교하는 조건을 통해서 해당 조건에 만족하는 행들만 모아놓은 데이터 프레임을 생성할 수 있다.
# query 함수 안에 pandas에서 검색을 위해 정한 문법대로 조건 문자열을 작성하면
# 이를 토대로 조건에 만족하는 행들을 가져올 수 있다.
# 조건 문자열안에 따옴표 없이 작성한 문자열은 컬럼의 이름으로 취급하고 띄어쓰기가 있으면 안된다.
df2 = df1.query('국어 > 90')
df2

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

In [11]:
# 수학점수가 70 이하인 것을 가져온다.
df2 = df1.query('수학 < 70')
df2

   이름  학년  성별  국어    영어    수학    과학
1  영희   2  여자  88  90.0  62.0  72.0
3  수현   3  여자  63  60.0  31.0  70.0

In [12]:
# 3학년 이상의 행만 가져온다
df2 = df1.query('학년 >= 3')
df2

   이름  학년  성별   국어    영어    수학    과학
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [13]:
# and : 두 조건이 만족하는 행만 가져온다.
df2 = df1.query('국어 > 80 and 수학 >80')
df2

   이름  학년  성별  국어  영어    수학    과학
0  철수   1  남자  98 NaN  88.0  64.0

In [14]:
# or : 둘 중 하나라도 만족하면 가져온다
df2 = df1.query('국어 < 70 or 수학 < 70')
df2

   이름  학년  성별  국어    영어    수학    과학
1  영희   2  여자  88  90.0  62.0  72.0
3  수현   3  여자  63  60.0  31.0  70.0

In [15]:
df2= df1[(df1['국어'] < 70) | (df1['수학'] < 70)]
df2

   이름  학년  성별  국어    영어    수학    과학
1  영희   2  여자  88  90.0  62.0  72.0
3  수현   3  여자  63  60.0  31.0  70.0

In [24]:
# 조건 문자열에 변수가 가지고 있는 값을 사용해야 한다면
a1 = 90

df2 = df1.query(f'국어 > {a1}')
display(df2)

# query 함수에 들어가는 조건 문자열에서 변수의 값을 사용하고 싶다면
# 변수명 앞에 @를 붙여주면 된다.
df3 = df1.query('국어 > @a1')
display(df3)

print(f'국어 > {a1}')

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

국어 > 90

In [27]:
# 만약에 컬럼에 있는 값과 같아야 하는 값들이 여러가지가 있을 경우
df2 = df1.query('이름 in ["철수","영희","민수"]')
display(df2)

list1 = ['철수','영희','민수']
df3 = df1.query('이름 in @list1')
display(df3)

   이름  학년  성별  국어    영어    수학    과학
0  철수   1  남자  98   NaN  88.0  64.0
2  민수   1  남자  92  70.0   NaN   NaN

   이름  학년  성별  국어    영어    수학    과학
0  철수   1  남자  98   NaN  88.0  64.0
2  민수   1  남자  92  70.0   NaN   NaN

In [47]:
# 포함하지 않는다고 하면
df2 = df1.query('이름 not in @list1')
df2

   이름  학년  성별   국어    영어    수학    과학
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [48]:
# 컬럼과 컬럼간의 비교
# 따옴표로 묶어주지 않으면 컬럼 이름에 해당한다.
# 국어 점수가 영어 점수보다 큰 행들을 가져온다.
df2 = df1.query('국어 > 영어')
df2

   이름  학년  성별   국어    영어    수학    과학
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [51]:
# 조건 문자열에 문자열 값을 사용하겠다면..

# 조건 문자열 내에 따옴표 없이 작성하면 컬럼 이름으로 취급한다.
# 만약 문자열 값을 사용하고자 한다면 따옴표로 묶어줘야 한다.
df2 = df1.query('성별 == "남자"')
df2

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
2  민수   1  남자   92  70.0   NaN   NaN
4  호영   4  남자  120  50.0   NaN  88.0

In [52]:
# 결측치가 있는 행을 가져오고 싶다면..
# 영어 컬럼에 결측치가 있는 행을 가져온다.
# 아래는 pandas에서 제공하는 함수를 사용하는 방법
df2 = df1.query('영어.isna()')
df2

   이름  학년  성별  국어  영어    수학    과학
0  철수   1  남자  98 NaN  88.0  64.0

In [53]:
# 결측치가 아닌 행들만 가져온다.
df2 = df1.query('영어.notna()')
df2

   이름  학년  성별   국어    영어    수학    과학
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

### 특정 컬럼을 인덱스로 지정한다.

In [54]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [56]:
# 이름 컬럼을 index로 지정한다.

# 지정한 컬럼이 데이터 프레임에서 제거되고 index로 지정된다.
df2 = df1.copy()
df2.set_index('이름', inplace=True)

display(df1)
display(df2)

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [64]:
# index를 초기화 한다.
df3 = df2.copy()

# index가 컬럼으로 포함되고 0 부터 1씩 증가하는 형태의 index로 셋팅된다.
df3.reset_index(inplace=True)
display(df2)
display(df3)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [65]:
df3.reset_index(inplace=True)
display(df3)

   index  이름  학년  성별   국어    영어    수학    과학
0      0  철수   1  남자   98   NaN  88.0  64.0
1      1  영희   2  여자   88  90.0  62.0  72.0
2      2  민수   1  남자   92  70.0   NaN   NaN
3      3  수현   3  여자   63  60.0  31.0  70.0
4      4  호영   4  남자  120  50.0   NaN  88.0

In [66]:
df3.reset_index(inplace=True)
display(df3)

   level_0  index  이름  학년  성별   국어    영어    수학    과학
0        0      0  철수   1  남자   98   NaN  88.0  64.0
1        1      1  영희   2  여자   88  90.0  62.0  72.0
2        2      2  민수   1  남자   92  70.0   NaN   NaN
3        3      3  수현   3  여자   63  60.0  31.0  70.0
4        4      4  호영   4  남자  120  50.0   NaN  88.0

In [69]:
# reset_index 시 index가 컬럼으로 포함될 때 level_0 이라는 이름의 컬럼으로 추가가 됬다면 
# reset_index를 또 하면 오류가 발생
df3.reset_index(inplace=True)
display(df3)

ValueError: cannot insert level_0, already exists

In [71]:
# index를 리셋 시킬 떄 원래의 index를 컬럼에 포함시키지 않겠다면
df3 = df2.copy()
df3 .reset_index(inplace=True, drop=True)

display(df2)
display(df3)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

   학년  성별   국어    영어    수학    과학
0   1  남자   98   NaN  88.0  64.0
1   2  여자   88  90.0  62.0  72.0
2   1  남자   92  70.0   NaN   NaN
3   3  여자   63  60.0  31.0  70.0
4   4  남자  120  50.0   NaN  88.0