### 값을 변경하거나 추가

In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [3]:
# 철수 행의 모든 컬럼의 값을 변경한다
# 모든 컬럼에 들어갈 값들을 지정해줘야 한다.
df2 =df1.copy()

df2.loc['철수'] = [5,'외계인',2000,3000,4000,5000]

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년   성별    국어      영어      수학      과학
이름
철수   5  외계인  2000  3000.0  4000.0  5000.0
영희   2   여자    88    90.0    62.0    72.0
민수   1   남자    92    70.0     NaN     NaN
수현   3   여자    63    60.0    31.0    70.0
호영   4   남자   120    50.0     NaN    88.0

In [4]:
# 특정 컬럼의 모든 행의 값을 변경한다.
# 행의 개수와 동일하게 값을 지정해야 한다.
df2 = df1.copy()
df2['과학'] = [100,200,300,400,500]
df2

    학년  성별   국어    영어    수학   과학
이름
철수   1  남자   98   NaN  88.0  100
영희   2  여자   88  90.0  62.0  200
민수   1  남자   92  70.0   NaN  300
수현   3  여자   63  60.0  31.0  400
호영   4  남자  120  50.0   NaN  500

In [5]:
# 특정 컬럼의 일부 행만 변경한다
# 민수, 수현의 국어 점수를 변경한다.
df2 = df1.copy()

df2.loc[['민수','수현'],'국어'] = [1000,2000]
df2

    학년  성별    국어    영어    수학    과학
이름
철수   1  남자    98   NaN  88.0  64.0
영희   2  여자    88  90.0  62.0  72.0
민수   1  남자  1000  70.0   NaN   NaN
수현   3  여자  2000  60.0  31.0  70.0
호영   4  남자   120  50.0   NaN  88.0

In [6]:
# 특정 행의 컬럼 일부만 변경한다.
df2 = df1.copy()
df2.loc['호영', ['국어','영어']] = [1000,2000]

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별    국어      영어    수학    과학
이름
철수   1  남자    98     NaN  88.0  64.0
영희   2  여자    88    90.0  62.0  72.0
민수   1  남자    92    70.0   NaN   NaN
수현   3  여자    63    60.0  31.0  70.0
호영   4  남자  1000  2000.0   NaN  88.0

In [7]:
# 일부 행, 일부 열의 값을 변경한다.
# 영희, 민수의 수학, 과학 점수를 변경한다.
df2 = df1.copy()
df2.loc[['영희','민수'],['수학','과학']] =[[100,200],[300,400]]
display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어     수학     과학
이름
철수   1  남자   98   NaN   88.0   64.0
영희   2  여자   88  90.0  100.0  200.0
민수   1  남자   92  70.0  300.0  400.0
수현   3  여자   63  60.0   31.0   70.0
호영   4  남자  120  50.0    NaN   88.0

In [8]:
# 없는 index를 지정하여 값을 넣어주면 행이 추가된다.
# 이 때, 넣어주는 값의 개수가 컬럼의 개수와 동일해야 한다.
display(df1)

df1.loc['영민'] = [5, '오징어',1,2,3,4]
display(df1)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년   성별   국어    영어    수학    과학
이름
철수   1   남자   98   NaN  88.0  64.0
영희   2   여자   88  90.0  62.0  72.0
민수   1   남자   92  70.0   NaN   NaN
수현   3   여자   63  60.0  31.0  70.0
호영   4   남자  120  50.0   NaN  88.0
영민   5  오징어    1   2.0   3.0   4.0

In [9]:
# 없는 이름의 컬럼을 통해 값을 넣어주면 컬럼이 추가된다.
# 이 때, 컬럼의 모든 행에 값을 지정해야 한다.
display(df1)

df1['한국사'] = [1,2,3,4,5,6]
df1

    학년   성별   국어    영어    수학    과학
이름
철수   1   남자   98   NaN  88.0  64.0
영희   2   여자   88  90.0  62.0  72.0
민수   1   남자   92  70.0   NaN   NaN
수현   3   여자   63  60.0  31.0  70.0
호영   4   남자  120  50.0   NaN  88.0
영민   5  오징어    1   2.0   3.0   4.0

    학년   성별   국어    영어    수학    과학  한국사
이름
철수   1   남자   98   NaN  88.0  64.0    1
영희   2   여자   88  90.0  62.0  72.0    2
민수   1   남자   92  70.0   NaN   NaN    3
수현   3   여자   63  60.0  31.0  70.0    4
호영   4   남자  120  50.0   NaN  88.0    5
영민   5  오징어    1   2.0   3.0   4.0    6

In [12]:
# 딕셔너리를 통한 값 변경
a1 = {
    '국어' : 1000,
    '수학' : 2000
}
display(df1)

# 딕셔너리를 지정해서 값을 변경하면 지정된 곳은 지정된 값으로 설정되지만
# 나머지는 모두 결측치로 변경된다.
# 행이나 컬럼을 추가할 떄 쓰면 좋음
df1.loc['철수'] = a1
display(df1)

     학년   성별    국어    영어      수학    과학  한국사
이름
철수  NaN  NaN  1000   NaN  2000.0   NaN  NaN
영희  2.0   여자    88  90.0    62.0  72.0  2.0
민수  1.0   남자    92  70.0     NaN   NaN  3.0
수현  3.0   여자    63  60.0    31.0  70.0  4.0
호영  4.0   남자   120  50.0     NaN  88.0  5.0
영민  5.0  오징어     1   2.0     3.0   4.0  6.0

     학년   성별    국어    영어      수학    과학  한국사
이름
철수  NaN  NaN  1000   NaN  2000.0   NaN  NaN
영희  2.0   여자    88  90.0    62.0  72.0  2.0
민수  1.0   남자    92  70.0     NaN   NaN  3.0
수현  3.0   여자    63  60.0    31.0  70.0  4.0
호영  4.0   남자   120  50.0     NaN  88.0  5.0
영민  5.0  오징어     1   2.0     3.0   4.0  6.0

In [15]:
# 딕셔너리를 통해 값을 지정하는 것은 새로운 행이나 컬럼을 추가할 때
# 사용하는 것이 일반적이다.

df1.loc['태풍'] = {
    '국어' : 100,
    '수학' : 200
}

display(df1)

df1['물리'] = {
    '호영' : 50,
    '민수' : 60
}
display(df1)

     학년   성별    국어    영어      수학    과학  한국사    물리
이름
철수  NaN  NaN  1000   NaN  2000.0   NaN  NaN   NaN
영희  2.0   여자    88  90.0    62.0  72.0  2.0   NaN
민수  1.0   남자    92  70.0     NaN   NaN  3.0  60.0
수현  3.0   여자    63  60.0    31.0  70.0  4.0   NaN
호영  4.0   남자   120  50.0     NaN  88.0  5.0  50.0
영민  5.0  오징어     1   2.0     3.0   4.0  6.0   NaN
태풍  NaN  NaN   100   NaN   200.0   NaN  NaN   NaN

     학년   성별    국어    영어      수학    과학  한국사    물리
이름
철수  NaN  NaN  1000   NaN  2000.0   NaN  NaN   NaN
영희  2.0   여자    88  90.0    62.0  72.0  2.0   NaN
민수  1.0   남자    92  70.0     NaN   NaN  3.0  60.0
수현  3.0   여자    63  60.0    31.0  70.0  4.0   NaN
호영  4.0   남자   120  50.0     NaN  88.0  5.0  50.0
영민  5.0  오징어     1   2.0     3.0   4.0  6.0   NaN
태풍  NaN  NaN   100   NaN   200.0   NaN  NaN   NaN

### 데이터 프레임 병합

In [16]:
# 테스트를 위해서 grade.csv를 통해 데이터 프레임을 생성하고
# 행을 하나 추가한 다음
# 행 두 개씩 해서 3개의 데이터 프레임을 생성한다.
temp_df = pd.read_csv('data/grade.csv', encoding='euc-kr')
temp_df.set_index('이름',inplace=True)
temp_df.loc['민호'] = [1,'남자',50,60,70,80]

df1 = temp_df.loc[['철수', '영희']]
df2 = temp_df.loc[['민수', '수현']]
df3 = temp_df.loc[['호영', '민호']]

display(df1)
display(df2)
display(df3)

    학년  성별  국어    영어    수학    과학
이름
철수   1  남자  98   NaN  88.0  64.0
영희   2  여자  88  90.0  62.0  72.0

    학년  성별  국어    영어    수학    과학
이름
민수   1  남자  92  70.0   NaN   NaN
수현   3  여자  63  60.0  31.0  70.0

    학년  성별   국어    영어    수학    과학
이름
호영   4  남자  120  50.0   NaN  88.0
민호   1  남자   50  60.0  70.0  80.0

In [18]:
# 데이터 프레임 병합
# 위에서 아래 방향으로 병합된다.
df100 = pd.concat([df1,df2,df3])
df100

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0
민호   1  남자   50  60.0  70.0  80.0

In [20]:
df200 = df2[['국어','영어','수학','과학','학년','성별']]

# concat 함수로 데이터 프레임을 병합하면
# 각 데이터 프레임의 컬럼 순서에 관계 없이 이름이 동일한 컬럼끼리 매칭하여 병합한다.
df100 = pd.concat([df1,df200,df3])

display(df200)
display(df100)

    국어    영어    수학    과학  학년  성별
이름
민수  92  70.0   NaN   NaN   1  남자
수현  63  60.0  31.0  70.0   3  여자

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0
민호   1  남자   50  60.0  70.0  80.0

In [22]:
# 만약 병합하고자 하는 데이터 프레임들의 컬럼이 동일하지 않는다면..
# 병합이 되고 컬럼이 없는 쪽은 결측치로 채워진다.
df200 = df2.copy()
df200['한국사'] = [100,200]

df100 = pd.concat([df1,df200,df3])
df100

    학년  성별   국어    영어    수학    과학    한국사
이름
철수   1  남자   98   NaN  88.0  64.0    NaN
영희   2  여자   88  90.0  62.0  72.0    NaN
민수   1  남자   92  70.0   NaN   NaN  100.0
수현   3  여자   63  60.0  31.0  70.0  200.0
호영   4  남자  120  50.0   NaN  88.0    NaN
민호   1  남자   50  60.0  70.0  80.0    NaN

In [28]:
# merge 테스트 : 데이터 베이스의 join과 동일하다.
# merger 테스트를 위해 데이터 프레임을 생성한다.
a1 = {
    '고객번호' : [1001,1002,1003,1005],
    '주소지' : ['서울','부산','대구','경기'],
    '이름' : ['홍길동','김길동','최길동','고길동']
}

a2 = {
    '고객번호' : [1001,1002,1003,1004],
    '배송지' : ['서울','부산','대구','대전'],
    '금액' : [10000,20000,30000,40000]
}

df1 = pd.DataFrame(a1)
df2 = pd.DataFrame(a2)

display(df1)
display(df2)

   고객번호 주소지   이름
0  1001  서울  홍길동
1  1002  부산  김길동
2  1003  대구  최길동
3  1005  경기  고길동

   고객번호 배송지     금액
0  1001  서울  10000
1  1002  부산  20000
2  1003  대구  30000
3  1004  대전  40000

In [30]:
# merge 사용
# merge는 join 조건으로 사용할 각 데이터 프레임의 컬럼들을 지정해줘야 한다.
# 만약 생략시 두 데이터 프레임의 컬럼들 중 이름이 같은 컬럼으로 자동 지정된다.
# 데이터 베이스의 inner join과 동일하다
# join 조건으로 지정된 두 컬럼의 값이 똑같은 것만 가져오고 다른 부분은 가져오지 않는다.
df10 = pd.merge(df1,df2)
df10

   고객번호 주소지   이름 배송지     금액
0  1001  서울  홍길동  서울  10000
1  1002  부산  김길동  부산  20000
2  1003  대구  최길동  대구  30000

In [31]:
# 만약 join 조건으로 사용할 두 컬럼의 이름이 서로 다르다면 지정해 줘야 한다.
# left_on : 좌측 데이터 프레임의 컬럼 이름
# right_on : 우측 데이터 프레임의 컬럼 이름
df20 = pd.merge(df1,df2,left_on='주소지', right_on='배송지')
df20

   고객번호_x 주소지   이름  고객번호_y 배송지     금액
0    1001  서울  홍길동    1001  서울  10000
1    1002  부산  김길동    1002  부산  20000
2    1003  대구  최길동    1003  대구  30000

In [32]:
# full outer join
# 두 데이터 프레임에 서로 없는 것들 까지도 포함한다.
# 없는 쪽은 결측치로 채워진다.
df30 = pd.merge(df1,df2, how='outer')
df30

   고객번호  주소지   이름  배송지       금액
0  1001   서울  홍길동   서울  10000.0
1  1002   부산  김길동   부산  20000.0
2  1003   대구  최길동   대구  30000.0
3  1004  NaN  NaN   대전  40000.0
4  1005   경기  고길동  NaN      NaN

In [33]:
# left outer join
# 좌측 데이터 프레임에는 있지만 우측 데이터 프레임에는 없는 것도 포함된다.
# 우측 데이터 프레임에는 있지만 좌측 데이터 프레임에 없는 것은 제외된다.
df100 = pd.merge(df1,df2,how='left')
df100

   고객번호 주소지   이름  배송지       금액
0  1001  서울  홍길동   서울  10000.0
1  1002  부산  김길동   부산  20000.0
2  1003  대구  최길동   대구  30000.0
3  1005  경기  고길동  NaN      NaN

In [34]:
# right outer join
# 우측 데이터 프레임에는 있지만 좌측 데이터 프레임에는 없는 것도 포함된다.
# 좌측 데이터 프레임에는 있지만 우측 데이터 프레임에는 없는 것은 제외된다.
df100 = pd.merge(df1,df2,how='right')
df100

   고객번호  주소지   이름 배송지     금액
0  1001   서울  홍길동  서울  10000
1  1002   부산  김길동  부산  20000
2  1003   대구  최길동  대구  30000
3  1004  NaN  NaN  대전  40000

### 삭제

In [35]:
df1 = pd.read_csv('data/grade.csv',encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [36]:
# 특정 행 하나만 삭제
df2 = df1.copy()
df2.drop('철수', inplace=True)

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [37]:
# 여러 행을 제거하고 싶다면...
df2 = df1.copy()
df2.drop(['민수','호영'],inplace=True)
display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별  국어    영어    수학    과학
이름
철수   1  남자  98   NaN  88.0  64.0
영희   2  여자  88  90.0  62.0  72.0
수현   3  여자  63  60.0  31.0  70.0

In [38]:
# axis에 1을 넣어주면 컬럼을 제거한다
df2 = df1.copy()
df2.drop('학년',inplace=True,axis=1)
df2

    성별   국어    영어    수학    과학
이름
철수  남자   98   NaN  88.0  64.0
영희  여자   88  90.0  62.0  72.0
민수  남자   92  70.0   NaN   NaN
수현  여자   63  60.0  31.0  70.0
호영  남자  120  50.0   NaN  88.0

In [39]:
# 여러 컬럼을 제거한다.
df2 = df1.copy()
df2.drop(['성별','수학'],inplace=True,axis=1)
df2

    학년   국어    영어    과학
이름
철수   1   98   NaN  64.0
영희   2   88  90.0  72.0
민수   1   92  70.0   NaN
수현   3   63  60.0  70.0
호영   4  120  50.0  88.0