In [1]:
import numpy as np
import pandas as pd

### 기초 통계 함수
- count() : 결측치를 제외한 데이터의 개수
- sum() : 결측치를 제외한 데이터의 총합
- mean() : 결측치를 제외한 평균
- median() : 결측치를 제외한 중앙값
- mode() : 결측치를 제외한 최빈값
- min() : 결측치를 제외한 최소값
- max() : 결측치를 제외한 최대값
- std() : 결측치를 제외한 표준편차
- var() : 결측치를 제외한 분산
- abs() : 절대값

### 누적 및 순위 관련 함수
- cumsum() : 누적합
- prod() : 누적곱
- sumprod() : 누적곱
- cummax() : 누적 최대값
- cummin() : 누적 최소값
- rank() : 순위 매기기

### 상관관계 및 공분산
- corr() : 피어슨 상관계수
- cov() : 공분산
- corrwith() : 두 DataFrame간의 상관계수

### 기타 통계 도움 함수들
- discribe() : 주요 통계량 요약
- quantile() : 분위수
- skwe() : 왜도
- kurt() : 첨도
- diff() : 바로 이전 행과 얼마나 차이가 나는지
- pct_change() : 바로 이전 행과의 차이를 비율로 표현 1 = 100%

In [3]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

### 요약 통계 정보

In [5]:
# 범위형(연속성 수치 데이터) 데이터에 대한 요약 통계 정보
df1[['국어','영어','수학','과학']].describe()

               국어         영어         수학         과학
count    5.000000   4.000000   3.000000   4.000000
mean    92.200000  67.500000  60.333333  73.500000
std     20.474374  17.078251  28.536526  10.246951
min     63.000000  50.000000  31.000000  64.000000
25%     88.000000  57.500000  46.500000  68.500000
50%     92.000000  65.000000  62.000000  71.000000
75%     98.000000  75.000000  75.000000  76.000000
max    120.000000  90.000000  88.000000  88.000000

- count : 결측치를 제외한 데이터의 개수
- mean : 결측치를 제외한 평균
- min : 결측치를 제외한 최소값
- std : 결측치를 제외한 표준 편차
- 25% : 결측치를 제외한 25% 위치의 값 또는 가까운 값
- 50% : 결측치를 제외한 50% 위치의 값 또는 가까운 값
- 75% : 결측치를 제외한 75% 위치의 값 또는 가까운 값
- max : 결측치를 제외한 최대 값

In [10]:
# 25%, 75%는 변경할 수 있다.
# 0 ~ 1 사이의 값을 넣어주면 0 위치는 min으로 1 위치는 max로 사용하면 되고
a1 = [0.0,0.1, 0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]
df1[['국어','영어','수학','과학']].describe(percentiles=a1)

               국어         영어         수학         과학
count    5.000000   4.000000   3.000000   4.000000
mean    92.200000  67.500000  60.333333  73.500000
std     20.474374  17.078251  28.536526  10.246951
min     63.000000  50.000000  31.000000  64.000000
0%      63.000000  50.000000  31.000000  64.000000
10%     73.000000  53.000000  37.200000  65.800000
20%     83.000000  56.000000  43.400000  67.600000
30%     88.800000  59.000000  49.600000  69.400000
40%     90.400000  62.000000  55.800000  70.400000
50%     92.000000  65.000000  62.000000  71.000000
60%     94.400000  68.000000  67.200000  71.600000
70%     96.800000  72.000000  72.400000  73.600000
80%    102.400000  78.000000  77.600000  78.400000
90%    111.200000  84.000000  82.800000  83.200000
100%   120.000000  90.000000  88.000000  88.000000
max    120.000000  90.000000  88.000000  88.000000

In [18]:
# 범주형 데이터에 대한 요약 통계 정보

# 데이터 프레임안에 숫자 컬럼이 있을 경우 describe함수를 사용하면
# 숫자 컬럼만 모아 범위형 데이터에 대한 요약 통계정보를 보여준다.
# 모든 컬럼들을 문자열로 변환한 데이터 프레임을 구해 함수를 사용한다.

# 허나 범주형 데이터에 대한 요약 통계 정보를 통해 사용할 만한 중요한 데이터는
# 사실상 없다고 보면된다. (다른 것들을 통해 직접 구해 쓰는 것이 낫다)
df1[['학년','성별']].astype('str').describe()

       학년  성별
count   5   5
unique  4   2
top     1  남자
freq    2   3

- count : 결측치를 제외한 데이터의 개수
- unique : 중복을 제외한 데이터의 개수
- top : 가장 많이 나온 데이터
- freq : 가장 많이 나온 데이터가 몇 번 나왔는지

### Pandas 통계 함수 사용 방법

In [19]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름', inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [34]:
# 기초 통계 함수들
print('결측치를 제외한 데이터의 개수')
a1 = df1.count()
print(a1)
print('-'*30)

# 연속성을 가진 수치형 데이터만 추출해 데이터 프레임으로 만든다.
df2 = df1[['국어','수학','영어','과학']]

print('결측치를 제외한 평균')
a1 = df2.mean()
print(a1)
print('-'*30)

print('결측치를 제외한 최소 값')
a1 = df2.min()
print(a1)
print('-'*30)

print('결측치를 제외한 표준편차')
a1 = df2.std()
print(a1)
print('-'*30)

print('결측치를 제외한 분산')
a1 =df2.var()
print(a1)
print('-'*30)

print('결측치를 제외한 50% 위치 값')
a1 = df2.quantile()
print(a1)
print('-'*30)

print('결측치를 제외한 중앙값')
a1 = df2.median()
print(a1)
print('-'*30)

print('결측치를 제외한 10% 위치 값')
a1 = df2.quantile(q=0.1)
print(a1)
print('-'*30)

print('결측치를 제외한 10%,20%,30% 위치 값')
a1 = df2.quantile(q=[0.1,0.2,0.3])
display(a1)
print('-'*30)

결측치를 제외한 데이터의 개수
학년    5
성별    5
국어    5
영어    4
수학    3
과학    4
dtype: int64
------------------------------
결측치를 제외한 평균
국어    92.200000
수학    60.333333
영어    67.500000
과학    73.500000
dtype: float64
------------------------------
결측치를 제외한 최소 값
국어    63.0
수학    31.0
영어    50.0
과학    64.0
dtype: float64
------------------------------
결측치를 제외한 표준편차
국어    20.474374
수학    28.536526
영어    17.078251
과학    10.246951
dtype: float64
------------------------------
결측치를 제외한 분산
국어    419.200000
수학    814.333333
영어    291.666667
과학    105.000000
dtype: float64
------------------------------
결측치를 제외한 50% 위치 값
국어    92.0
수학    62.0
영어    65.0
과학    71.0
Name: 0.5, dtype: float64
------------------------------
결측치를 제외한 중앙값
국어    92.0
수학    62.0
영어    65.0
과학    71.0
dtype: float64
------------------------------
결측치를 제외한 10% 위치 값
국어    73.0
수학    37.2
영어    53.0
과학    65.8
Name: 0.1, dtype: float64
------------------------------
결측치를 제외한 10%,20%,30% 위치 값

       국어    수학    영어    과학
0.1  73.0  37.2  53.0  65.8
0.2  83.0  43.4  56.0  67.6
0.3  88.8  49.6  59.0  69.4

------------------------------

In [35]:
# 동시에 여러 통계값을 구하고자 한다면~
# agg 함수안에 구하고자 하는 통계값을 구할 수 있는 함수의 이름을 문자열로 넣어준다.
df2.agg(['min','max','count'])

        국어    수학    영어    과학
min     63  31.0  50.0  64.0
max    120  88.0  90.0  88.0
count    5   3.0   4.0   4.0

In [36]:
# 만약 각 컬럼별로 다른 통계 값을 구하고 싶다면~
d1 = {
    '국어' : ['min','max'],
    '영어' : ['sum','mean']
}

df2.agg(d1)

         국어     영어
min    63.0    NaN
max   120.0    NaN
sum     NaN  270.0
mean    NaN   67.5