In [1]:
import numpy as np
import pandas as pd

In [2]:
# 데이터 프레임 생성
df1 = pd.read_csv('data/city_people.csv', encoding='euc-kr')
df1

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권
6  인천  2015  2890451  수도권
7  인천  2010  2632035  수도권

In [7]:
# groupby : 지정된 컬럼을 기준으로 그룹을 묶어준다.
# 컬럼 내의 값이 같은 것 끼리 하나의 그룹으로 묶인다.

# ( 그룹의 기준이 되는 값, 그 그룹으로 묶인 행들의 데이터 프레임) 형태로 각 그룹별 튜플이 만들어지고 그 튜플들을 관리하는 객체가 생성된다.
# 이 객체 안에는 각 그룹별로 통계량 값을 구할 수 있는 함수들이 제공된다.
a1 = df1.groupby('도시')
list(a1)

for c1, temp_df in a1 :
    display(c1)
    display(temp_df)
    display('-'*30)

'부산'

   도시    연도       인구   지역
3  부산  2015  3448737  경상권
4  부산  2010  3393191  경상권
5  부산  2005  3512547  경상권

'------------------------------'

'서울'

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
1  서울  2010  9631482  수도권
2  서울  2005  9762546  수도권

'------------------------------'

'인천'

   도시    연도       인구   지역
6  인천  2015  2890451  수도권
7  인천  2010  2632035  수도권

'------------------------------'

In [8]:
# 그룹의 기준이 되는 컬럼은 여러개를 설정할 수도 있다.
a1 = df1.groupby(['지역','연도'])

for c1, temp_df in a1 :
    display(c1)
    display(temp_df)
    display('-'*30)

('경상권', 2005)

   도시    연도       인구   지역
5  부산  2005  3512547  경상권

'------------------------------'

('경상권', 2010)

   도시    연도       인구   지역
4  부산  2010  3393191  경상권

'------------------------------'

('경상권', 2015)

   도시    연도       인구   지역
3  부산  2015  3448737  경상권

'------------------------------'

('수도권', 2005)

   도시    연도       인구   지역
2  서울  2005  9762546  수도권

'------------------------------'

('수도권', 2010)

   도시    연도       인구   지역
1  서울  2010  9631482  수도권
7  인천  2010  2632035  수도권

'------------------------------'

('수도권', 2015)

   도시    연도       인구   지역
0  서울  2015  9904312  수도권
6  인천  2015  2890451  수도권

'------------------------------'

In [12]:
# 도시를 기준으로 인구 최대 값을 구한다.
# 방법1 : 값을 구하기 위해 필요한 컬럼들과 그룹을 묶기 위해 필요한 컬럼들을 추출한다음
# 그룹으로 묶고 통계값을 구하는 방법
df2 = df1[['도시','인구']]
df2.groupby('도시').max()

         인구
도시
부산  3512547
서울  9904312
인천  2890451

In [13]:
# 방법2 : 먼저 그룹을 묶고 값을 구하기 위한 컬럼을 가져와 통계값을 구한다.
df1.groupby('도시')['인구'].max()

도시
부산    3512547
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [20]:
df2 = df1[['도시','인구']]
list(df2.groupby('도시'))[0][1]

   도시       인구
3  부산  3448737
4  부산  3393191
5  부산  3512547

In [23]:
df1.groupby('도시')['인구'].max()

도시
부산    3512547
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [26]:
df2 = df1[['도시','연도','인구']]
df2.groupby('도시').max()

      연도       인구
도시
부산  2015  3512547
서울  2015  9904312
인천  2015  2890451

In [27]:
df1.groupby('도시')[['연도','인구']].max()

      연도       인구
도시
부산  2015  3512547
서울  2015  9904312
인천  2015  2890451

In [28]:
# 그룹의 기준을 다수로 두고 통계량 값을 구한다면~
df2 = df1[['연도','인구','지역']]

r2 = df2.groupby(['지역','연도']).max()
r2

               인구
지역  연도
경상권 2005  3512547
    2010  3393191
    2015  3448737
수도권 2005  9762546
    2010  9631482
    2015  9904312

In [31]:
r2.loc['경상권'].loc[2010]

인구    3393191
Name: 2010, dtype: int64

In [37]:
# 기준이 되는 컬럼은 결과에 인덱스로 빠지게 된다.
# 만약 그룹의 기준이 되는 컬럼들도 결과에 포함하고자 한다면~
df2 = df1[['도시','인구']]
r1 = df2.groupby('도시', as_index=False).max()
display(r1)

df3 = df1[['지역','연도','인구']]
r2 =df3.groupby(['지역','연도'], as_index=False).max()
display(r2)

   도시       인구
0  부산  3512547
1  서울  9904312
2  인천  2890451

    지역    연도       인구
0  경상권  2005  3512547
1  경상권  2010  3393191
2  경상권  2015  3448737
3  수도권  2005  9762546
4  수도권  2010  9631482
5  수도권  2015  9904312

### 여러 통계값을 동시에 구하기

In [38]:
df2 = df1[['도시','인구']]

r1 = df2.groupby('도시').agg(['min','max','std','median'])
r1

         인구
        min      max            std     median
도시
부산  3393191  3512547   59725.663038  3448737.0
서울  9631482  9904312  136449.978473  9762546.0
인천  2632035  2890451  182727.705967  2761243.0

In [40]:
r1.loc['서울','인구'].loc['max']

np.float64(9904312.0)

In [41]:
# 각 컬럼별 통계값을 다르게 구할 경우
df2 = df1[['도시','인구','지역']]

a1 = {
    '도시' : ['count'],
    '인구' : ['sum','max']
}

r2 =df2.groupby('지역').agg(a1)
r2

       도시        인구
    count       sum      max
지역
경상권     3  10354475  3512547
수도권     5  34820826  9904312

In [43]:
print(r2.loc['경상권','도시'].loc['count'])
print(r2.loc['수도권','인구'].loc['sum'])

3
34820826