### 결측치와 이상치 처리 방법
- 제거 : 결측치나 이상치를 가진 데이터를 제거한다.
- 제거를 하게 되면 데이터의 왜곡이 발생하지 않지만 데이터 양이 줄어든다.
- 대체 : 결측치나 이상치를 다른 값으로 바꾸는 것을 의미한다.
- 대체를 하게 되면 데이터의 양이 줄어들지는 않지만 왜곡이 발생할 수 있다.

In [1]:
import numpy as np
import pandas as pd

### 결측치 확인

In [2]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1

   이름  학년  성별   국어    영어    수학    과학
0  철수   1  남자   98   NaN  88.0  64.0
1  영희   2  여자   88  90.0  62.0  72.0
2  민수   1  남자   92  70.0   NaN   NaN
3  수현   3  여자   63  60.0  31.0  70.0
4  호영   4  남자  120  50.0   NaN  88.0

In [3]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [4]:
# 각 컬럼별 결측의 개수를 확인한다.
a1 = df1.isna().sum()
a1[a1>0]

영어    1
수학    2
과학    1
dtype: int64

### 결측치 제거

In [5]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [6]:
# 결측치가 포함된 모든 행을 제거한다.
df2 = df1.copy()

df2.dropna(inplace=True)

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별  국어    영어    수학    과학
이름
영희   2  여자  88  90.0  62.0  72.0
수현   3  여자  63  60.0  31.0  70.0

In [7]:
# 컬럼을 지정하여 그 컬럼들에 결측치가 있는 행들을 제거한다.
df2 = df1.copy()

df2.dropna(inplace=True,subset=['수학','과학'])
display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별  국어    영어    수학    과학
이름
철수   1  남자  98   NaN  88.0  64.0
영희   2  여자  88  90.0  62.0  72.0
수현   3  여자  63  60.0  31.0  70.0

In [8]:
# 모든 컬럼에 결측치가 있는 행을 삭제한다.
df2 = df1.copy()

df2.loc['길동'] = [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]
display(df2)

df2.dropna(inplace=True, how='all')
display(df2)

     학년   성별     국어    영어    수학    과학
이름
철수  1.0   남자   98.0   NaN  88.0  64.0
영희  2.0   여자   88.0  90.0  62.0  72.0
민수  1.0   남자   92.0  70.0   NaN   NaN
수현  3.0   여자   63.0  60.0  31.0  70.0
호영  4.0   남자  120.0  50.0   NaN  88.0
길동  NaN  NaN    NaN   NaN   NaN   NaN

     학년  성별     국어    영어    수학    과학
이름
철수  1.0  남자   98.0   NaN  88.0  64.0
영희  2.0  여자   88.0  90.0  62.0  72.0
민수  1.0  남자   92.0  70.0   NaN   NaN
수현  3.0  여자   63.0  60.0  31.0  70.0
호영  4.0  남자  120.0  50.0   NaN  88.0

In [9]:
# 결측치가 있는 모든 컬럼을 삭제한다.
df2 = df1.copy()
df2.dropna(inplace=True, axis=1)

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어
이름
철수   1  남자   98
영희   2  여자   88
민수   1  남자   92
수현   3  여자   63
호영   4  남자  120

In [10]:
# index를 지정하여 결측치가 있는 컬럼을 삭제한다.
df2 = df1.copy()

df2.dropna(inplace=True, axis=1, subset=['민수','호영'])
display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어
이름
철수   1  남자   98   NaN
영희   2  여자   88  90.0
민수   1  남자   92  70.0
수현   3  여자   63  60.0
호영   4  남자  120  50.0

### 결측치 대체

In [11]:
# 모든 결측치에 동일한 값을 채워준다
df2 = df1.copy()

df2.fillna(value=50, inplace=True)

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98  50.0  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0  50.0  50.0
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0  50.0  88.0

In [12]:
# 컬럼별로 다른 값을 채워준다.
df2 = df1.copy()

df2['영어'].fillna(value=50,inplace=True)
df2['수학'].fillna(value=60,inplace=True)
df2['과학'].fillna(value=70,inplace=True)

display(df1)
display(df2)

C:\Users\dokim\AppData\Local\Temp\ipykernel_25300\1474449884.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['영어'].fillna(value=50,inplace=True)
C:\Users\dokim\AppData\Local\Temp\ipykernel_25300\1474449884.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['수학'].fillna(value=60,inplace=True)
C:\Users\dokim\AppData\Local\Temp\ipykernel_25300\1474449884.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df2['과학'].fillna(value=70,inplace=True)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [13]:
# 위의 방법은 새롭게 생성된 Series를 통해 작업을 하는 것이기 때문에 원본 데이터 프레임에는 반영되지 않는다.
# (pandas 2.x에서는 반영을 해주었음)
# 아래와 같이 작업해야한다.
df2 = df1.copy()

df2['영어'] = df2['영어'].fillna(value=50)
df2['수학'] = df2['수학'].fillna(value=60)
df2['과학'] = df2['과학'].fillna(value=70)

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98  50.0  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0  60.0  70.0
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0  60.0  88.0

### 이상치 확인
- 연속형 수치 데이터 : 정상 범위를 벗어나는 값
- 범주형 데이터 : 정상 종류의 값이 아닌 값
- 사회 통념상 상식적인 값으로 판단할 수도 있지만 **데이터 명세서가 우선**이다.
- 극단치는 이상치일 가능성이 있다.
- 반드시 데이터 명세서를 확인해야 한다.
- 이상치라는 것은 데이터 명세서에 나와있는 정상적인 값에 위배되는 값을 의미한다.

In [14]:
df1 = pd.read_csv('data/grade.csv', encoding='euc-kr')
df1.set_index('이름',inplace=True)
df1

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

In [15]:
# 범주형 데이터에 대한 이상치 확인
# 각 컬럼별로 어떠한 값들이 있는지 확인한다.
# 데이터 명세서와 비교해서 다른 부분이 있는지 확인해볼 수 있음
display(df1['학년'].value_counts().index)
display(df1['성별'].value_counts().index)

Index([1, 2, 3, 4], dtype='int64', name='학년')

Index(['남자', '여자'], dtype='str', name='성별')

In [16]:
# unique 함수를 사용해도 되지만 결측치가 있을 경우 결측치로 표시된다.
# 데이터 명세서와 비교해서 다른 부분이 있는지 확인해볼 수 있음
display(df1['학년'].unique())
display(df1['성별'].unique())

array([1, 2, 3, 4])

<StringArray>
['남자', '여자']
Length: 2, dtype: str

In [17]:
# 범위형 데이터 (연속성을 가지고 있는 수치형 데이터)에 대한 이상치 확인
a1 = df1[['국어','수학','영어','과학']].describe()
a1.loc[['min','max']]

        국어    수학    영어    과학
min   63.0  31.0  50.0  64.0
max  120.0  88.0  90.0  88.0

In [18]:
# 통계함수를 이용해 최대와 최소를 구해 확인한다.
df1[['국어','수학','영어','과학']].agg(['min','max'])

      국어    수학    영어    과학
min   63  31.0  50.0  64.0
max  120  88.0  90.0  88.0

### 극단치
- 통계학에서 대부분의 데이터 분포와 다른 분포를 보이는 데이터
- 극단치 경계를 벗어나는 데이터를 의미한다.
- IQR = Q3(75% 위치값) - Q1(25% 위치값)
- 극단치 최소 경계 = Q1 - (1.5 * IQR)
- 극단치 최대 경계 = Q3 + (1.5 * IQR)

In [19]:
# Q1 값
Q1 = df1['국어'].quantile(q=0.25)
# Q3 값
Q3 = df1['국어'].quantile(q=0.75)

In [20]:
# IQR
IQR = Q3 - Q1
IQR

np.float64(10.0)

In [21]:
# 극단치 최소 경계
outliner_min = Q1 - (1.5*IQR)
# 극단치 최대 경계
outliner_max = Q3 + (1.5*IQR)

print(outliner_min,outliner_max)

73.0 113.0

In [22]:
# 극단치에 해당하는 행을 가져온다.
a1 = df1.query('국어 < @outliner_min or 국어 > @outliner_max')
a1

    학년  성별   국어    영어    수학    과학
이름
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

### 이상치 처리

In [23]:
# 정상 범위를 벗어나는 행을 확인한다.
df2 = df1.copy()

idx = df2.query('국어 < 0 or 국어> 100').index
display(idx)
# idx에 해당하는 행을 모두 제거한다.
df2.drop(idx,inplace=True)

display(df1)
display(df2)

Index(['호영'], dtype='str', name='이름')

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별  국어    영어    수학    과학
이름
철수   1  남자  98   NaN  88.0  64.0
영희   2  여자  88  90.0  62.0  72.0
민수   1  남자  92  70.0   NaN   NaN
수현   3  여자  63  60.0  31.0  70.0

In [25]:
# 대체
df2 = df1.copy()

# 이상치라고 판단되는 값을 가진 행의 index를 추출한다
idx = df2.query('국어 < 0 or 국어 > 100').index

df2.loc[idx, '국어'] = 100

display(df1)
display(df2)

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  120  50.0   NaN  88.0

    학년  성별   국어    영어    수학    과학
이름
철수   1  남자   98   NaN  88.0  64.0
영희   2  여자   88  90.0  62.0  72.0
민수   1  남자   92  70.0   NaN   NaN
수현   3  여자   63  60.0  31.0  70.0
호영   4  남자  100  50.0   NaN  88.0