In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 관련 ################################################
# 결측치 처리
from sklearn.impute import SimpleImputer
# 표준화
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
# 인코더
from sklearn.preprocessing import LabelEncoder
# 원핫 인코더
from sklearn.preprocessing import OneHotEncoder

# 학습 모델 성능 관련 #######################################
# 원하는 비율로 데이터를 나누기 위해
from sklearn.model_selection import train_test_split
# K-Fold 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
# 학습 곡선
from sklearn.model_selection import learning_curve
# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint
import optuna
from optuna.samplers import TPESampler
from optuna.pruners import MedianPruner
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 모델 성능 평가 ########################
# 회귀용
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score
# 분류용
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve
from sklearn.metrics import auc
from sklearn.metrics import roc_auc_score
from sklearn.metrics import ConfusionMatrixDisplay

# 피처 선택 #########################
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import RFE
from sklearn.inspection import permutation_importance

# 학습 모델 ########################
# 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier 
from sklearn.naive_bayes import GaussianNB
from catboost import CatBoostClassifier

# 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.linear_model import BayesianRidge
from catboost import CatBoostRegressor

# 결정트리를 시각화할 수 있는 라이브러리
from sklearn.tree import plot_tree

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.manifold import TSNE

# 연관 규칙 학습
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from sklearn.mixture import GaussianMixture
from sklearn.cluster import MeanShift, estimate_bandwidth

# 파이프라인
from sklearn.pipeline import Pipeline

# KDE를 그리기 위한 통계값을 구할 수 있는 함수
from scipy.stats import gaussian_kde

# 피어슨 상관 계수 (연속형 수치형 데이터 vs 연속형 수치형 데이터)
from scipy.stats import pearsonr
# 카이제곱 검증 (범주형 데이터 vs 범주형 데이터, 순위X)
from scipy.stats import chi2_contingency
# 스피어만 상관계수 (범주형 데이터 vs 범주형 데이터, 순위O)
from scipy.stats import spearmanr
# 포인트 이분 상관계수 (범주형 데이터 vs 연속형 수치형 데이터)
from scipy.stats import pointbiserialr

# 오버 샘플링
from imblearn.over_sampling import SMOTE

# 객체를 파일에 저장
import pickle

# 문장 데이터 관련
# 단어 토큰화
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
# 정규식 사용
import re
# 불용어 처리
from nltk.corpus import stopwords

# 불필요한 경고 뜨지 않게
import warnings
warnings.filterwarnings('ignore')

### 불용어 처리 예시

In [2]:
# 영어 불용어 리스트를 가져온다.
stop_words = set(stopwords.words('english'))
print(stop_words)

{'and', 'couldn', 'ma', 'aren', 'we', 'between', 'doing', "they've", 'further', 'its', 'so', 'nor', 'hers', 'into', 'i', 'their', "she'll", 'just', 'at', 'to', 've', 'too', 'm', "we're", 'few', "he'll", 'who', 'such', 'her', "couldn't", 'him', "i'll", 'been', 'that', 'theirs', 'o', 'no', 'can', 'wasn', 'them', "we'd", 'weren', 'about', 'haven', 'won', 'how', 'very', 'more', 'an', 'only', 'don', "you'd", 'does', "i've", 't', 'be', "we'll", "don't", 'had', 'he', 'if', 'shan', 'has', 'did', 'a', 'any', 'not', 'mustn', "mustn't", 'now', 'out', "they'll", 'which', 'then', 'doesn', 'll', 'these', 'all', 'when', "aren't", 'most', 'what', 'hasn', "he's", 'same', 'are', 'ourselves', 'have', 'here', 'shouldn', 'down', 'through', 'off', 'while', 'should', 'again', 'needn', 'than', "won't", "it'll", 'with', 'me', 'below', 'she', 'was', 'himself', 're', 'once', 's', 'during', 'yourself', 'myself', 'in', "it's", 'above', 'is', 'yourselves', 'do', 'itself', 'but', 'those', 'wouldn', 'by', 'd', 'they', "you're", "you'll", 'mightn', "they're", 'our', "doesn't", 'isn', 'some', 'for', "haven't", "she's", 'the', "weren't", "shan't", 'of', 'this', 'why', 'up', 'on', "they'd", 'before', 'will', "wouldn't", 'each', "hasn't", 'hadn', 'didn', "he'd", "needn't", 'or', "she'd", "you've", "that'll", "i'd", "hadn't", "didn't", 'herself', 'until', 'there', 'your', 'were', 'having', 'yours', 'my', 'ain', "we've", "should've", 'after', "shouldn't", "it'd", 'other', 'ours', 'under', "isn't", 'over', 'his', 'as', 'being', "i'm", 'own', 'themselves', 'you', 'because', 'from', 'where', 'it', 'against', "mightn't", "wasn't", 'y', 'whom', 'am', 'both'}

In [3]:
# 예시 문장 (앞서 노이즈 제거를 마친 상태를 가정)
example_sentence = "This is a free entry in a contest to win a prize"

In [4]:
# 토큰화
words = word_tokenize(example_sentence.lower())
print(words)

['this', 'is', 'a', 'free', 'entry', 'in', 'a', 'contest', 'to', 'win', 'a', 'prize']

In [5]:
# 불용어 필터링
filtered_sentence = [w for w in words if w not in stop_words]
filtered_sentence

['free', 'entry', 'contest', 'win', 'prize']

### 스팸 문자 데이터에 적용

In [6]:
df = pd.read_csv('data/spam4.csv', encoding='latin-1')
df

,label,text,tokenized_text,clean_text
0,ham,"Go until jurong point, crazy.. Available only ...","['Go', 'until', 'jurong', 'point', ',', 'crazy...",Go until jurong point crazy Available only in ...
1,ham,Ok lar... Joking wif u oni...,"['Ok', 'lar', '...', 'Joking', 'wif', 'u', 'on...",Ok lar Joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,"['Free', 'entry', 'in', '2', 'a', 'wkly', 'com...",Free entry in a wkly comp to win FA Cup final ...
3,ham,U dun say so early hor... U c already then say...,"['U', 'dun', 'say', 'so', 'early', 'hor', '......",U dun say so early hor U c already then say
4,ham,"Nah I don't think he goes to usf, he lives aro...","['Nah', 'I', 'do', ""n't"", 'think', 'he', 'goes...",Nah I don t think he goes to usf he lives arou...
...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,"['This', 'is', 'the', '2nd', 'time', 'we', 'ha...",This is the nd time we have tried contact u U ...
5568,ham,Will Ì_ b going to esplanade fr home?,"['Will', 'Ì_', 'b', 'going', 'to', 'esplanade'...",Will b going to esplanade fr home
5569,ham,"Pity, * was in mood for that. So...any other s...","['Pity', ',', '*', 'was', 'in', 'mood', 'for',...",Pity was in mood for that So any other suggest...
5570,ham,The guy did some bitching but I acted like i'd...,"['The', 'guy', 'did', 'some', 'bitching', 'but...",The guy did some bitching but I acted like i d...
5571,ham,Rofl. Its true to its name,"['Rofl', '.', 'Its', 'true', 'to', 'its', 'name']",Rofl Its true to its name

In [7]:
# 앞서 저장할 때 데이터 프레임에 있던 리스트는 그 자체로 문자열로 저장된다.
# 해당 문자열로 저장된 리스트 데이터를 진짜 리스트 데이터로 가져온다.
from ast import literal_eval
df['tokenized_text'] = df['tokenized_text'].apply(literal_eval)

In [8]:
# 불용어를 가져온다.
stop_words = set(stopwords.words('english'))

In [9]:
# 만약 추가적인 불용어가 있다면 다음과 같이 추가한다.
custom_stopwords = {'u', 'ur', '2', '4', 'free', 'txt', 'stop'}
stop_words.update(custom_stopwords)
print(stop_words)
# 제거하고 싶다면 stop_words.remove('단어')함수를 사용한다.

{'and', 'couldn', 'ma', 'aren', 'we', 'between', 'doing', "they've", 'further', 'its', 'so', 'nor', 'hers', 'into', 'i', 'their', "she'll", 'just', 'at', 'to', 've', 'too', 'm', "we're", 'few', "he'll", 'who', 'such', 'her', "couldn't", 'him', "i'll", 'been', 'that', 'theirs', 'o', 'no', 'can', 'wasn', 'them', "we'd", 'weren', 'about', 'haven', 'won', 'how', 'very', 'more', 'an', 'only', 'don', "you'd", 'does', 'stop', "i've", 't', 'be', "we'll", "don't", 'ur', 'had', 'he', 'if', 'shan', 'has', 'did', 'a', 'any', 'not', 'mustn', "mustn't", 'now', 'out', "they'll", 'which', 'then', 'doesn', 'll', 'these', 'all', 'when', "aren't", 'most', 'what', 'hasn', "he's", 'same', 'u', 'are', 'ourselves', 'have', 'here', 'shouldn', 'down', 'through', 'off', 'while', 'should', 'again', 'needn', 'than', "won't", "it'll", 'with', 'me', 'below', 'she', 'was', 'himself', 're', 'once', 's', 'during', 'yourself', 'myself', 'in', "it's", 'above', 'is', 'yourselves', 'do', 'itself', 'but', 'those', 'wouldn', 'by', 'd', 'they', "you're", "you'll", 'mightn', "they're", 'our', "doesn't", 'isn', 'some', 'for', "haven't", "she's", 'the', "weren't", "shan't", 'of', 'this', 'why', 'up', 'on', "they'd", 'before', 'will', "wouldn't", 'each', "hasn't", 'hadn', 'didn', "he'd", "needn't", 'or', "she'd", "you've", "that'll", "i'd", "hadn't", "didn't", 'herself', 'until', 'there', 'your', 'were', 'having', 'yours', 'my', 'ain', "we've", "should've", 'after', 'txt', "shouldn't", "it'd", 'other', 'ours', 'under', "isn't", 'over', 'his', 'as', 'being', "i'm", 'own', 'themselves', 'you', 'because', 'from', 'where', 'it', 'against', "mightn't", '4', "wasn't", 'y', '2', 'whom', 'free', 'am', 'both'}

In [10]:
# 불용어 제거 함수 (토큰화 되어 있는 단어 리스를 받는다)
def filter_stopwords(token_list) :
    # 이미 토큰화된 리스트를 받아서
    # 소문자로 변환
    # 비교
    # 불용어 사전에 없는 단어만 남긴
    # 특수문자만 있느 토큰 제외(isalpha)
    return [word for word in token_list if word.lower() not in stop_words and word.isalpha()]

In [11]:
df['clean_tokens'] = df['tokenized_text'].apply(filter_stopwords)
df

,label,text,tokenized_text,clean_text,clean_tokens
0,ham,"Go until jurong point, crazy.. Available only ...","[Go, until, jurong, point, ,, crazy, .., Avail...",Go until jurong point crazy Available only in ...,"[Go, jurong, point, crazy, Available, bugis, n..."
1,ham,Ok lar... Joking wif u oni...,"[Ok, lar, ..., Joking, wif, u, oni, ...]",Ok lar Joking wif u oni,"[Ok, lar, Joking, wif, oni]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...",Free entry in a wkly comp to win FA Cup final ...,"[entry, wkly, comp, win, FA, Cup, final, tkts,..."
3,ham,U dun say so early hor... U c already then say...,"[U, dun, say, so, early, hor, ..., U, c, alrea...",U dun say so early hor U c already then say,"[dun, say, early, hor, c, already, say]"
4,ham,"Nah I don't think he goes to usf, he lives aro...","[Nah, I, do, n't, think, he, goes, to, usf, ,,...",Nah I don t think he goes to usf he lives arou...,"[Nah, think, goes, usf, lives, around, though]"
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,"[This, is, the, 2nd, time, we, have, tried, 2,...",This is the nd time we have tried contact u U ...,"[time, tried, contact, Pound, prize, claim, ea..."
5568,ham,Will Ì_ b going to esplanade fr home?,"[Will, Ì_, b, going, to, esplanade, fr, home, ?]",Will b going to esplanade fr home,"[b, going, esplanade, fr, home]"
5569,ham,"Pity, * was in mood for that. So...any other s...","[Pity, ,, *, was, in, mood, for, that, ., So, ...",Pity was in mood for that So any other suggest...,"[Pity, mood, suggestions]"
5570,ham,The guy did some bitching but I acted like i'd...,"[The, guy, did, some, bitching, but, I, acted,...",The guy did some bitching but I acted like i d...,"[guy, bitching, acted, like, interested, buyin..."
5571,ham,Rofl. Its true to its name,"[Rofl, ., Its, true, to, its, name]",Rofl Its true to its name,"[Rofl, true, name]"

In [12]:
df.to_csv('data/spam5.csv', encoding='latin-1', index=False)